//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Website.Admi.Users
{


    public partial class UserAdmin
    {

        /// <summary>
        /// AccountSummarySection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel AccountSummarySection;

        /// <summary>
        /// rbxAccountSummaryPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.AccountSummaryPane rbxAccountSummaryPane;

        /// <summary>
        /// BillingInfoSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel BillingInfoSection;

        /// <summary>
        /// rbxBillingInfoPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.BillingInfoPane rbxBillingInfoPane;

        /// <summary>
        /// PunishmentsSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PunishmentsSection;

        /// <summary>
        /// rbxPunishmentsPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.PunishmentsPane rbxPunishmentsPane;

        /// <summary>
        /// ProfileRatingsSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ProfileRatingsSection;

        /// <summary>
        /// UserNotesSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel UserNotesSection;

        /// <summary>
        /// rbxUserNotesPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.UserNotesPane rbxUserNotesPane;

        /// <summary>
        /// UpdateUserSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel UpdateUserSection;

        /// <summary>
        /// rbxUpdateUserPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.UpdateUserPane rbxUpdateUserPane;

        /// <summary>
        /// GiveAndTakeSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel GiveAndTakeSection;

        /// <summary>
        /// rbxGiveAndTakePane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.GiveAndTakePane rbxGiveAndTakePane;
    }
}
