//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Website
{


    public partial class UserPage
    {

        /// <summary>
        /// rbxHeaderPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.HeaderPane rbxHeaderPane;

        /// <summary>
        /// OBCmember control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl OBCmember;

        /// <summary>
        /// rbxUserPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.UserPane rbxUserPane;

        /// <summary>
        /// rbxUserBadgesPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.UserBadgesPane rbxUserBadgesPane;

        /// <summary>
        /// rbxBadgesDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.BadgesDisplay rbxBadgesDisplay;

        /// <summary>
        /// rbxUserGroupsPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.UserGroupsPane rbxUserGroupsPane;

        /// <summary>
        /// rbxUserStatisticsPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.UserStatisticsPane rbxUserStatisticsPane;

        /// <summary>
        /// rbxSetsPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.SetsPane rbxSetsPane;

        /// <summary>
        /// rbxUserPlacesPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.UserContent.UserPlacesPane rbxUserPlacesPane;
    }
}
