using System.Web;
using System.Web.Optimization;
using Roblox.Web.StaticContent;

namespace Roblox.Website {
	public class BundleConfig
	{
		// For more information on bundling, visit https://go.microsoft.com/fwlink/?LinkId=301862
		public static void RegisterBundles(BundleCollection bundles)
		{

			BundleTable.EnableOptimizations = true;
			RobloxScripts.MergeFiles = WebsiteSettings.Properties.Settings.Default.MergeJavaScriptFiles;
			RobloxCSS.MergeFiles = WebsiteSettings.Properties.Settings.Default.MergeCSS;

			bundles.UseCdn = true;   // enable CDN support

			bundles.Add(new ScriptBundle("~/Js/M/Default").Include(
			   "~/js/jquery/jquery-1.7.2.min.js",
			   "~/js/Microsoft/MicrosoftAjax.js",
			   "~/js/jquery/jquery-ui-1.9.2.min.js"));

			bundles.Add(new ScriptBundle("~/Bundles/jQuery", "//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.2.min.js").Include(
			   "~/js/jquery/jquery-1.7.2.min.js"));
			bundles.Add(new ScriptBundle("~/Bundles/Ajax", "//ajax.aspnetcdn.com/ajax/4.0/1/MicrosoftAjax.js").Include(
			   "~/js/Microsoft/MicrosoftAjax.js"));

			StaticContent.CreateScriptBundle(
				"master",
					"roblox.js",
					"jquery.json-2.2.js",
					"jquery.simplemodal-1.3.5.js",
					"jquery.tipsy.js",
					"AjaxAvatarThumbnail.js",
					"extensions/string.js",
					"StringTruncator.js",
					"json2.js",
					"webkit.js",
					"GoogleAnalytics/GoogleAnalyticsEvents.js",
					"MasterPageUI.js",
					"jquery.cookie.js",
					"jquery.jsoncookie.js",
					"JSErrorTracker.js",
					"RobloxEventManager.js",
					"RobloxEventListener.js",
					"GoogleEventListener.js",
					"MongoEventListener.js",
					"SiteTouchEvent.js",
					"jPlayer/2.4.0/jquery.jplayer.js",
					"XsrfToken.js",
					"jquery.ba-postmessage.js",
					"parentFrameLogin.js",
					"DropDownNav.js",
					"UpsellAdModal.js"
			);

			StaticContent.CreateScriptBundle(
				"base",
					"roblox.js",
					"jquery.json-2.2.js",
					"jquery.simplemodal-1.3.5.js",
					"jquery.tipsy.js",
					"AjaxAvatarThumbnail.js",
					"extensions/string.js",
					"StringTruncator.js",
					"json2.js",
					"webkit.js",
					"GoogleAnalytics/GoogleAnalyticsEvents.js",
					"MasterPageUI.js",
					"jquery.cookie.js",
					"jquery.jsoncookie.js",
					"JSErrorTracker.js",
					"XsrfToken.js",
					"RobloxEventManager.js",
					"RobloxEventListener.js",
					"GoogleEventListener.js",
					"MongoEventListener.js",
					"SiteTouchEvent.js",
					"GPTAdScript.js",
					"DropDownNav.js",
					"common/forms.js",
					"jquery.ba-postmessage.js",
					"parentFrameLogin.js",
					"UpsellAdModal.js"
			);
			StaticContent.CreateScriptBundle(
				"simple",
					"jquery.simplemodal-1.3.5.js",
					"jquery.tipsy.js",
					"GoogleAnalytics/GoogleAnalyticsEvents.js",
					"json2.js",
					"jquery.cookie.js",
					"jquery.jsoncookie.js",
					"DropDownNav.js",
					"JSErrorTracker.js",
					"RobloxEventManager.js",
					"RobloxEventListener.js",
					"GoogleEventListener.js",
					"MongoEventListener.js",
					"SiteTouchEvent.js",
					"GenericConfirmation.js",
					"UpsellAdModal.js"
			);
			StaticContent.CreateScriptBundle(
				"simple-mvc",
					"RobloxEventManager.js",
					"jquery.simplemodal-1.3.5.js",
					"jquery.cookies.2.2.0.1.js",
					"jquery.cookie.js",
					"jquery.jsoncookie.js",
					"jquery.json-2.2.js",
					"parentFrameLogin.js",
					"RobloxEventListener.js",
					"GoogleEventListener.js",
					"MongoEventListener.js",
					"SiteTouchEvent.js",
					"JSErrorTracker.js"
			);
			StaticContent.CreateScriptBundle(
				"videopreroll",
					"VideoPreRoll.js"
			);
			StaticContent.CreateScriptBundle(
				"clientinstaller",
					"EventTracker.js",
					"ClientInstaller.js",
					"InstallationInstructions.js",
					"IEMetroInstructions.js"
			);
			StaticContent.CreateScriptBundle(
				"placelauncher",
					"CharacterSelect.js",
					"MadStatus.js",
					"PlaceLauncher.js",
					"ABPlaceLauncher.js"
			);
			StaticContent.CreateScriptBundle(
				"nonLoggedIn",
					"jquery.ba-postmessage.js",
					"parentFrameLogin.js"
			);
			StaticContent.CreateScriptBundle(
				"chat",
					"jquery.cookies.2.2.0.1.js",
					"chat.js",
					"jquery-extensions.js",
					"party.js"
			);
			StaticContent.CreateScriptBundle(
				"threeDeeThumbnailScripts",
					"3D/three.js",
					"3D/MTLLoader.js",
					"3D/OBJMTLLoader.js",
					"3D/tween.js",
					"3D/RobloxOrbitControls.js"
			);
			StaticContent.CreateScriptBundle(
				"jQuery",
					"modules/jQuery.js"
			);
			StaticContent.CreateScriptBundle(
				 "iframelogin",
					"jquery.ba-postmessage.js",
					"iFrameLogin.js"
			);

			StaticContent.CreateCSSBundle(
				"main",
					"Base/CSS/Roblox.css",
					"RBXCommon.css",
					"Base/CSS/AdFormatClasses.css",
					"Base/CSS/Ads.css",
					"Base/CSS/AgeUpEmailVerifyPage.css",
					"Base/CSS/Asset.css",
					"Base/CSS/Badges.css",
					"Base/CSS/BCModal.css",
					"Base/CSS/Billing.css",
					"Base/CSS/carouselpager.css",
					"Base/CSS/Catalog.css",
					"Base/CSS/CharacterCustomization.css",
					"Base/CSS/CharacterSelectAndInstallInstructions.css",
					"Base/CSS/CommonForms.css",
					"Base/CSS/ContentAdapters.css",
					"Base/CSS/ContentBuilder.css",
					"Base/CSS/Contest.css",
					"Base/CSS/CreditCardExpireModal.css",
					"Base/CSS/CuratedGames.css",
					"Base/CSS/CurrencyExchange.css",
					"Base/CSS/Flyouts.css",
					"Base/CSS/Footer.css",
					"Base/CSS/Games.css",
					"Base/CSS/GenericModal.css",
					"Base/CSS/GroupRoleSetMembersPane.css",
					"Base/CSS/Groups.css",
					"Base/CSS/Header.css",
					"Base/CSS/Help.css",
					"Base/CSS/IframeHeader.css",
					"Base/CSS/iFrameLogin.css",
					"Base/CSS/Install.css",
					"Base/CSS/Item.css",
					"Base/CSS/jquery.mCustomScrollbar.css",
					"Base/CSS/LandingGames.css",
					"Base/CSS/Language.css",
					"Base/CSS/LoadingSpinner.css",
					"Base/CSS/ManageAccount.css",
					"Base/CSS/MediaThumb.css",
					"Base/CSS/Membership.css",
					"Base/CSS/MenuRedesign.css",
					"Base/CSS/Message.css",
					"Base/CSS/Modals.css",
					"Base/CSS/MyAccount.css",
					"Base/CSS/MyItem.css",
					"Base/CSS/MyMoney.css",
					"Base/CSS/NewToolBox.css",
					"Base/CSS/Parents.css",
					"Base/CSS/party.css",
					"Base/CSS/PersonalServerAccessPrivilegesRoleSet.css",
					"Base/CSS/Place.css",
					"Base/CSS/PlaceItem.css",
					"Base/CSS/PlaceLauncher.css",
					"Base/CSS/Profile.css",
					"Base/CSS/RevisedCharacterSelectModal.css",
					"Base/CSS/Sets.css",
					"Base/CSS/ShadowedStandardBox.css",
					"Base/CSS/ShareRoblox.css",
					"Base/CSS/Signup.css",
					"Base/CSS/tipsy.css",
					"Base/CSS/Thumbnail.css",
					"Base/CSS/tipsy.css",
					"Base/CSS/Toolbox.css",
					"Base/CSS/Trade.css",
					"Base/CSS/UnifiedModal.css",
					"Base/CSS/Upgrades.css",
					"Base/CSS/Upload.css",
					"Base/CSS/User.css",
					"Base/CSS/Utility.css",
					"Base/CSS/VideoPreRoll.css",
					"Base/CSS/StyleGuide.css",
					"RBX2/CSS/DarkGradientBox.css",
					"RBX2/CSS/Item.css",
					"RBX2/CSS/Roblox.css",
					"RBX2/CSS/Utility.css"
			);

			StaticContent.CreateCSSBundle(
				"reset",
					"~/CSS/YUIReset.css"
			);

			/*bundles.Add(new StyleBundle("~/App_Themes/RobloxDefault").Include(
				"~/App_Themes/RobloxDefault/Badges.css",
				"~/App_Themes/RobloxDefault/Frontpage.css",
				"~/App_Themes/RobloxDefault/Inbox.css",
				"~/App_Themes/RobloxDefault/Info.css",
				"~/App_Themes/RobloxDefault/Install.css",
				"~/App_Themes/RobloxDefault/Membership.css",
				"~/App_Themes/RobloxDefault/Message.css",
				"~/App_Themes/RobloxDefault/Profile.css",
				"~/App_Themes/RobloxDefault/ShareRoblox.css",
				"~/App_Themes/RobloxDefault/Splash.css",
				"~/App_Themes/RobloxDefault/Toolbox.css",
				"~/App_Themes/RobloxDefault/User.css"));*/
		}
	}
}
