//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Website.UserControls.Admi.Users
{


    public partial class CheatDetections
    {

        /// <summary>
        /// pnlCheatDetections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Controls.Panel pnlCheatDetections;

        /// <summary>
        /// rbxCheatDetectionsTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Roblox.Website.UserControls.Admi.UserAdmin.CheatDetectionsTable rbxCheatDetectionsTable;
    }
}
