//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Authentication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Authentication.Login", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Logged In Device.
        /// </summary>
        internal static string Action_AnotherLoggedInDevice {
            get {
                return ResourceManager.GetString("Action.AnotherLoggedInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Log In.
        /// </summary>
        internal static string Action_DeviceCode {
            get {
                return ResourceManager.GetString("Action.DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Action_Facebook {
            get {
                return ResourceManager.GetString("Action.Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password or username?.
        /// </summary>
        internal static string Action_ForgotPasswordOrUsernameQuestion {
            get {
                return ResourceManager.GetString("Action.ForgotPasswordOrUsernameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password or Username?.
        /// </summary>
        internal static string Action_ForgotPasswordOrUsernameQuestionCapitalized {
            get {
                return ResourceManager.GetString("Action.ForgotPasswordOrUsernameQuestionCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Action_ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("Action.ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Action_Login {
            get {
                return ResourceManager.GetString("Action.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Action_LogInCapitalized {
            get {
                return ResourceManager.GetString("Action.LogInCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        internal static string Action_LoginWithFacebook {
            get {
                return ResourceManager.GetString("Action.LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_Ok {
            get {
                return ResourceManager.GetString("Action.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as Guest.
        /// </summary>
        internal static string Action_PlayAsGuest {
            get {
                return ResourceManager.GetString("Action.PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ Login.
        /// </summary>
        internal static string Action_QQLogin {
            get {
                return ResourceManager.GetString("Action.QQLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string Action_Resend {
            get {
                return ResourceManager.GetString("Action.Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email.
        /// </summary>
        internal static string Action_ResendEmail {
            get {
                return ResourceManager.GetString("Action.ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Verification Email.
        /// </summary>
        internal static string Action_SendVerificationEmail {
            get {
                return ResourceManager.GetString("Action.SendVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Action_SignIn {
            get {
                return ResourceManager.GetString("Action.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In with Facebook.
        /// </summary>
        internal static string Action_SignInWithFacebook {
            get {
                return ResourceManager.GetString("Action.SignInWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Action_SignUp {
            get {
                return ResourceManager.GetString("Action.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Action_SignUpCapitalized {
            get {
                return ResourceManager.GetString("Action.SignUpCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up!.
        /// </summary>
        internal static string Action_SignUpCapitalizedExcited {
            get {
                return ResourceManager.GetString("Action.SignUpCapitalizedExcited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat Login.
        /// </summary>
        internal static string Action_WeChatLogin {
            get {
                return ResourceManager.GetString("Action.WeChatLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Heading_Login {
            get {
                return ResourceManager.GetString("Heading.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to ROBLOX.
        /// </summary>
        internal static string Heading_LoginRoblox {
            get {
                return ResourceManager.GetString("Heading.LoginRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up to Build &amp; Make Friends.
        /// </summary>
        internal static string Heading_SignUpMakeFriends {
            get {
                return ResourceManager.GetString("Heading.SignUpMakeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need an account to play ROBLOX.
        /// </summary>
        internal static string Label_AccountNotNeeded {
            get {
                return ResourceManager.GetString("Label.AccountNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to recover your account?.
        /// </summary>
        internal static string Label_AccountRecoveryPromptBody {
            get {
                return ResourceManager.GetString("Label.AccountRecoveryPromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email needs verification.
        /// </summary>
        internal static string Label_EmailNeedsVerification {
            get {
                return ResourceManager.GetString("Label.EmailNeedsVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have been signing in with Facebook, you must set a password..
        /// </summary>
        internal static string Label_FacebookCreatePasswordWarning {
            get {
                return ResourceManager.GetString("Label.FacebookCreatePasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username/Password?.
        /// </summary>
        internal static string Label_ForgotUsernamePassword {
            get {
                return ResourceManager.GetString("Label.ForgotUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice to meet you, {0}. Let&apos;s make an account!.
        /// </summary>
        internal static string Label_GreetingForNewAccount {
            get {
                return ResourceManager.GetString("Label.GreetingForNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string Label_LearnMore {
            get {
                return ResourceManager.GetString("Label.LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string Label_LoggingInSpinnerText {
            get {
                return ResourceManager.GetString("Label.LoggingInSpinnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login with.
        /// </summary>
        internal static string Label_LoginWithYour {
            get {
                return ResourceManager.GetString("Label.LoginWithYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string Label_NoAccount {
            get {
                return ResourceManager.GetString("Label.NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member?.
        /// </summary>
        internal static string Label_NonAMemberQuestion {
            get {
                return ResourceManager.GetString("Label.NonAMemberQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive it?.
        /// </summary>
        internal static string Label_NotReceived {
            get {
                return ResourceManager.GetString("Label.NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Label_Or {
            get {
                return ResourceManager.GetString("Label.Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Label_PasswordWithColumn {
            get {
                return ResourceManager.GetString("Label.PasswordWithColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start playing right now, in guest mode!.
        /// </summary>
        internal static string Label_StartPlaying {
            get {
                return ResourceManager.GetString("Label.StartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To log in with your email, it must be verified. You can also log in with your username..
        /// </summary>
        internal static string Label_UnverifiedEmailInstructions {
            get {
                return ResourceManager.GetString("Label.UnverifiedEmailInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Email.
        /// </summary>
        internal static string Label_UsernameEmail {
            get {
                return ResourceManager.GetString("Label.UsernameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Email/Phone.
        /// </summary>
        internal static string Label_UsernameEmailPhone {
            get {
                return ResourceManager.GetString("Label.UsernameEmailPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Phone.
        /// </summary>
        internal static string Label_UsernamePhone {
            get {
                return ResourceManager.GetString("Label.UsernamePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Label_UsernameWithColumn {
            get {
                return ResourceManager.GetString("Label.UsernameWithColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Email Sent!.
        /// </summary>
        internal static string Label_VerificationEmailSent {
            get {
                return ResourceManager.GetString("Label.VerificationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boycott bad games, refuse pirated games. Be aware of self-defense and being deceived. Playing games is good for your brain, but too much game play can harm your health. Manage your time well and enjoy a healthy lifestyle..
        /// </summary>
        internal static string Label_WeChatAntiAddictionText {
            get {
                return ResourceManager.GetString("Label.WeChatAntiAddictionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please try again..
        /// </summary>
        internal static string Message_UnknownErrorTryAgain {
            get {
                return ResourceManager.GetString("Message.UnknownErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password are required..
        /// </summary>
        internal static string Message_UsernameAndPasswordRequired {
            get {
                return ResourceManager.GetString("Message.UsernameAndPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account issue. Please contact Support..
        /// </summary>
        internal static string Response_AccountIssueErrorContactSupport {
            get {
                return ResourceManager.GetString("Response.AccountIssueErrorContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked. Please request a password reset..
        /// </summary>
        internal static string Response_AccountLockedRequestReset {
            get {
                return ResourceManager.GetString("Response.AccountLockedRequestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found. Please try again..
        /// </summary>
        internal static string Response_AccountNotFound {
            get {
                return ResourceManager.GetString("Response.AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is associated with more than 1 username. Please login with your username..
        /// </summary>
        internal static string Response_EmailLinkedToMultipleAccountsLoginWithUsername {
            get {
                return ResourceManager.GetString("Response.EmailLinkedToMultipleAccountsLoginWithUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent!.
        /// </summary>
        internal static string Response_EmailSent {
            get {
                return ResourceManager.GetString("Response.EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is unable to log in. Please log in to the LuoBu app..
        /// </summary>
        internal static string Response_GlobalAppAccessError {
            get {
                return ResourceManager.GetString("Response.GlobalAppAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        internal static string Response_IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("Response.IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone or password..
        /// </summary>
        internal static string Response_IncorrectPhoneOrPassword {
            get {
                return ResourceManager.GetString("Response.IncorrectPhoneOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect. Please check them and try again..
        /// </summary>
        internal static string Response_IncorrectUsernamePassword {
            get {
                return ResourceManager.GetString("Response.IncorrectUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please login with your username..
        /// </summary>
        internal static string Response_LoginWithUsername {
            get {
                return ResourceManager.GetString("Response.LoginWithUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        internal static string Response_PasswordNotProvided {
            get {
                return ResourceManager.GetString("Response.PasswordNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign ups have been disabled. Please try again later..
        /// </summary>
        internal static string Response_TencentSignupDisabled {
            get {
                return ResourceManager.GetString("Response.TencentSignupDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Please wait a bit..
        /// </summary>
        internal static string Response_TooManyAttemptsPleaseWait {
            get {
                return ResourceManager.GetString("Response.TooManyAttemptsPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string Response_UnknownError {
            get {
                return ResourceManager.GetString("Response.UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown login failure..
        /// </summary>
        internal static string Response_UnknownLoginError {
            get {
                return ResourceManager.GetString("Response.UnknownLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is not verified. Please login with your username..
        /// </summary>
        internal static string Response_UnverifiedEmailLoginWithUsername {
            get {
                return ResourceManager.GetString("Response.UnverifiedEmailLoginWithUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone is not verified. Please login with your username..
        /// </summary>
        internal static string Response_UnverifiedPhoneLoginWithUsername {
            get {
                return ResourceManager.GetString("Response.UnverifiedPhoneLoginWithUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a username..
        /// </summary>
        internal static string Response_UsernameNotProvided {
            get {
                return ResourceManager.GetString("Response.UsernameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login. Please use Social Network sign on..
        /// </summary>
        internal static string Response_UseSocialSignOn {
            get {
                return ResourceManager.GetString("Response.UseSocialSignOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error occurred during verification..
        /// </summary>
        internal static string Response_VerificationError {
            get {
                return ResourceManager.GetString("Response.VerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your WeChat is not real-name verified. Please use a real-name verified WeChat account and try again. Please play {url}.
        /// </summary>
        internal static string Response_WeChatNotRealNameVerified {
            get {
                return ResourceManager.GetString("Response.WeChatNotRealNameVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boycott bad games, refuse pirated games. Be aware of self-defense and being deceived. Playing games is good for your brain, but too much game play can harm your health. Manage your time well and enjoy a healthy lifestyle..
        /// </summary>
        internal static string WeChat_AntiAddictionText {
            get {
                return ResourceManager.GetString("WeChat.AntiAddictionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your WeChat is not real-name verified. Please use a real-name verified WeChat account and try again. Please play https://jiazhang.qq.com/zk/home.html&quot;.
        /// </summary>
        internal static string WeChat_RealNameNotVerified {
            get {
                return ResourceManager.GetString("WeChat.RealNameNotVerified", resourceCulture);
            }
        }
    }
}
