//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Website.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Authentication_ResetPassword {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authentication_ResetPassword() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roblox.Website.App_GlobalResources.Authentication.ResetPassword", typeof(Authentication_ResetPassword).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use email to reset password.
        /// </summary>
        internal static string Action_EmailToResetPassword {
            get {
                return ResourceManager.GetString("Action.EmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use email to retrieve username.
        /// </summary>
        internal static string Action_EmailToRetriveUsername {
            get {
                return ResourceManager.GetString("Action.EmailToRetriveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_Ok {
            get {
                return ResourceManager.GetString("Action.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use phone number to reset password.
        /// </summary>
        internal static string Action_PhoneToResetPassword {
            get {
                return ResourceManager.GetString("Action.PhoneToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use phone number to retrieve username.
        /// </summary>
        internal static string Action_PhoneToRetriveUsername {
            get {
                return ResourceManager.GetString("Action.PhoneToRetriveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Action_Verify {
            get {
                return ResourceManager.GetString("Action.Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to recover your account?.
        /// </summary>
        internal static string Description_AccountRecoveryPrompt_Body {
            get {
                return ResourceManager.GetString("Description.AccountRecoveryPrompt.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to reset your password..
        /// </summary>
        internal static string Description_EmailToResetPassword {
            get {
                return ResourceManager.GetString("Description.EmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to retrieve your username..
        /// </summary>
        internal static string Description_EmailToRetriveUsername {
            get {
                return ResourceManager.GetString("Description.EmailToRetriveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {username},&lt;br/&gt;&lt;br/&gt;We noticed you have changed the password for your account. If you didn&apos;t intend to change it, or you think someone else changed it by mistake, then we need you to contact customer support ({supportLink}) to change the password back. That way we will know for sure that your account is secure and safe.&lt;br/&gt;&lt;br/&gt;If you are happy with your new password on Roblox, you don&apos;t have to do anything! It&apos;s already set up.&lt;br/&gt;Please do not reply to this message. If you have any questions, plea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Description_PasswordChangeEmail_BodyHtml_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordChangeEmail.BodyHtml.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed that the password changed for your Roblox account: {userName}. If you didn&apos;t intend to change it, or you think someone else changed it by mistake, please click this link to undo the action:\n{urlWithTicket}\n\nIf you are happy with your new Roblox password, you don&apos;t have to do anything! It&apos;s already set up. Please do not reply to this message. If you have any questions, please see the Roblox help page (https://www.roblox.com/help)..
        /// </summary>
        internal static string Description_PasswordChangeEmail_BodyPlainText {
            get {
                return ResourceManager.GetString("Description.PasswordChangeEmail.BodyPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {username},\n\nWe noticed you have changed the password for your account. If you didn&apos;t intend to change it, or you think someone else changed it by mistake, then we need you to contact customer support ({supportLink}) to change the password back. That way we will know for sure that your account is secure and safe.\n\nIf you are happy with your new password on Roblox, you don&apos;t have to do anything! It&apos;s already set up.\nPlease do not reply to this message. If you have any questions, please see the Robl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Description_PasswordChangeEmail_BodyPlainText_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordChangeEmail.BodyPlainText.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;Roblox Password Reset\&quot; {fromEmailAddress}.
        /// </summary>
        internal static string Description_PasswordChangeEmail_From {
            get {
                return ResourceManager.GetString("Description.PasswordChangeEmail.From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed that the password changed for your Roblox account: {userName}. If you didn&apos;t intend to change it, or you think someone else changed it by mistake, please click this link to undo the action:&lt;br /&gt;&lt;a href=\&quot;{urlWithTicket}\&quot;&gt;{urlShown}&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;If you are happy with your new Roblox password, you don&apos;t have to do anything! It&apos;s already set up. Please do not reply to this message. If you have any questions, please see the Roblox help page (https://www.roblox.com/help)..
        /// </summary>
        internal static string Description_PasswordChangeEmail_HtmlBody {
            get {
                return ResourceManager.GetString("Description.PasswordChangeEmail.HtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Password Reset.
        /// </summary>
        internal static string Description_PasswordChangeEmail_Subject {
            get {
                return ResourceManager.GetString("Description.PasswordChangeEmail.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {paragraphStart}Hello,{paragraphEnd}{paragraphStart}We have received a request to reset the password for your Roblox account: {emphasisStart}{emailOrUsername}{emphasisEnd}.{paragraphEnd}{paragraphStart}If you submitted this request, please click the button below to proceed:{paragraphEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_Body_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.Body.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active for {passwordResetTicketHours} hour and {passwordResetTicketMinutes} minutes.{lineBreak}{paragraphStart}Thank You,{lineBreak}{emphasisStart}The Roblox Team{emphasisEnd}{paragraphEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_BodyLower_HourAndMinutes {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.BodyLower.HourAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active for {passwordResetTicketHours} hours and {passwordResetTicketMinutes} minutes.{lineBreak}{paragraphStart}Thank You,{lineBreak}{emphasisStart}The Roblox Team{emphasisEnd}{paragraphEnd}\t.
        /// </summary>
        internal static string Description_PasswordResetEmail_BodyLower_HoursAndMinutes {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.BodyLower.HoursAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active for {passwordResetTicketHours} hours.{lineBreak}{paragraphStart}Thank You,{lineBreak}{emphasisStart}The Roblox Team{emphasisEnd}{paragraphEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_BodyLower_HoursOnly {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.BodyLower.HoursOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active for {passwordResetTicketMinutes} minutes.{lineBreak}{paragraphStart}Thank You,{lineBreak}{emphasisStart}The Roblox Team{emphasisEnd}{paragraphEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_BodyLower_MinutesOnly {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.BodyLower.MinutesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active for 1 hour.{lineBreak}{paragraphStart}Thank You,{lineBreak}{emphasisStart}The Roblox Team{emphasisEnd}{paragraphEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_BodyLower_OneHourOnly {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.BodyLower.OneHourOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active for {passwordResetTicketHours} hour(s), {passwordResetTicketMinutes} minute(s).{lineBreak}{paragraphStart}Thank You,{lineBreak}{emphasisStart}The Roblox Team{emphasisEnd}{paragraphEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_BodyLower_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.BodyLower.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Description_PasswordResetEmail_ButtonText_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.ButtonText.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this email because there has been an attempt to reset your password. If you did not make this request, do not reply to this email directly. Please contact {aTagStartWithHref}{supportPageLink}{hrefEnd}Roblox Support{aTagEnd} and change your password immediately..
        /// </summary>
        internal static string Description_PasswordResetEmail_Footer_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.Footer.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this email as there was a request to reset your password. If you didn&apos;t make this request, you can just ignore this email. Please review our help article for more information on {aTagStartWithHref}{accountSecurityLink}{hrefEnd}Account Security{aTagEnd}. Do not reply to this email as it will not be received. If you need assistance, please visit us at {aTagStartWithHref}{supportPageLink}{hrefEnd}Roblox Support{aTagEnd}..
        /// </summary>
        internal static string Description_PasswordResetEmail_FooterUpdated_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.FooterUpdated.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {escapeLiteralStart}Roblox Password Reset{escapeLiteralEnd} {fromEmailAddress}.
        /// </summary>
        internal static string Description_PasswordResetEmail_From {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Account Password Reset.
        /// </summary>
        internal static string Description_PasswordResetEmail_Header_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.Header.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received a request to reset the password for your Roblox account: {emailOrUsername}{lineBreak}{lineBreak}If you submitted this request, please click the button below to proceed.{lineBreak}This button will be active for {passwordResetTicketHours} hours, {passwordResetTicketMinutes} minutes. If you do not wish to reset your password, please disregard this notice.{lineBreak}{lineBreak}{aTagWithStartHref}{resetPasswordUrl}{hrefEnd}{buttonStart}Reset Password{buttonEnd}{aTagEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_HtmlBody {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.HtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {aTagStartWithHref}{AccountSafetyArticleLink}{hrefEnd}Account Safety{aTagEnd} | {aTagStartWithHref}{supportPageLink}{hrefEnd}Support{aTagEnd}.
        /// </summary>
        internal static string Description_PasswordResetEmail_Links_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.Links.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received a request to reset the password for your Roblox account: {emailOrUsername}{lineBreak}{lineBreak}If you submitted this request, please click the link below or paste it into a web browser to proceed.{lineBreak}This link will be active for {passwordResetTicketHours} hours, {passwordResetTicketMinutes} minutes. If you do not wish to reset your password, please disregard this notice.{lineBreak}{lineBreak}{resetPasswordUrl}.
        /// </summary>
        internal static string Description_PasswordResetEmail_PlainBody {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.PlainBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Account Password Reset.
        /// </summary>
        internal static string Description_PasswordResetEmail_Subject {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Account Password Reset.
        /// </summary>
        internal static string Description_PasswordResetEmail_Subject_V2 {
            get {
                return ResourceManager.GetString("Description.PasswordResetEmail.Subject.V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to reset your password..
        /// </summary>
        internal static string Description_PhoneToResetPassword {
            get {
                return ResourceManager.GetString("Description.PhoneToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to retrieve your username..
        /// </summary>
        internal static string Description_PhoneToRetriveUsername {
            get {
                return ResourceManager.GetString("Description.PhoneToRetriveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username/Password?.
        /// </summary>
        internal static string Heading_AccountRecoveryPrompt_Title {
            get {
                return ResourceManager.GetString("Heading.AccountRecoveryPrompt.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username or password?.
        /// </summary>
        internal static string Heading_ForgotUsernameOrPassword {
            get {
                return ResourceManager.GetString("Heading.ForgotUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Code.
        /// </summary>
        internal static string Heading_VerifyCode {
            get {
                return ResourceManager.GetString("Heading.VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone.
        /// </summary>
        internal static string Heading_VerifyPhone {
            get {
                return ResourceManager.GetString("Heading.VerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password or Username.
        /// </summary>
        internal static string HeadingForgetPasswordOrUsername {
            get {
                return ResourceManager.GetString("HeadingForgetPasswordOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Label_ActionButtonYes {
            get {
                return ResourceManager.GetString("Label.ActionButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot My Password.
        /// </summary>
        internal static string Label_ForgetMyPassword {
            get {
                return ResourceManager.GetString("Label.ForgetMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot My Username.
        /// </summary>
        internal static string Label_ForgetMyUsername {
            get {
                return ResourceManager.GetString("Label.ForgetMyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string Label_InvalidEmail {
            get {
                return ResourceManager.GetString("Label.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        internal static string Label_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("Label.InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Label_NeutralButtonOk {
            get {
                return ResourceManager.GetString("Label.NeutralButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Code.
        /// </summary>
        internal static string Label_ResendCode {
            get {
                return ResourceManager.GetString("Label.ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Label_ResetPassword {
            get {
                return ResourceManager.GetString("Label.ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Label_Submit {
            get {
                return ResourceManager.GetString("Label.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting controls who can find you using the phone number you provided..
        /// </summary>
        internal static string Label_ToolTip_WhoCanFindMeByPhone {
            get {
                return ResourceManager.GetString("Label.ToolTip.WhoCanFindMeByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames Reminder.
        /// </summary>
        internal static string Label_UsernamesReminder {
            get {
                return ResourceManager.GetString("Label.UsernamesReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can find me by my phone number?.
        /// </summary>
        internal static string Label_WhoCanFindMeByPhone {
            get {
                return ResourceManager.GetString("Label.WhoCanFindMeByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account security ticket is expired..
        /// </summary>
        internal static string Message_AccountSecurityTicketExpired {
            get {
                return ResourceManager.GetString("Message.AccountSecurityTicketExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not give us a &lt;strong&gt;real email address&lt;/strong&gt; when you created your account, we cannot send you an email..
        /// </summary>
        internal static string Message_CantSendEmailWarning {
            get {
                return ResourceManager.GetString("Message.CantSendEmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, try again later..
        /// </summary>
        internal static string Message_DefaultError {
            get {
                return ResourceManager.GetString("Message.DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with your username(s) has been sent to you if the email was previously saved on your account..
        /// </summary>
        internal static string Message_EmailForUsernameSuccessBody {
            get {
                return ResourceManager.GetString("Message.EmailForUsernameSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with instructions has been sent to you if the email was previously saved on your account..
        /// </summary>
        internal static string Message_EmailSuccessBody {
            get {
                return ResourceManager.GetString("Message.EmailSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        internal static string Message_EmailSuccessTitle {
            get {
                return ResourceManager.GetString("Message.EmailSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code was sent to your phone if it was previously verified on your account. Please enter it below.
        /// </summary>
        internal static string Message_EnterCode {
            get {
                return ResourceManager.GetString("Message.EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code we just sent to your email..
        /// </summary>
        internal static string Message_EnterCodeSentToEmail {
            get {
                return ResourceManager.GetString("Message.EnterCodeSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can send you an email to remind you of your usernames or reset your password. Please enter your username or email and click one of the links below..
        /// </summary>
        internal static string Message_PasswordResetExplanation {
            get {
                return ResourceManager.GetString("Message.PasswordResetExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMS with your username(s) has been sent to you if the phone number was previously verified on your account..
        /// </summary>
        internal static string Message_PhoneForUsernameSuccessBody {
            get {
                return ResourceManager.GetString("Message.PhoneForUsernameSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Sent.
        /// </summary>
        internal static string Message_PhoneForUsernameSuccessTitle {
            get {
                return ResourceManager.GetString("Message.PhoneForUsernameSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no email linked to this account.
        /// </summary>
        internal static string MessageAccountDoesNotHaveAnEmail {
            get {
                return ResourceManager.GetString("MessageAccountDoesNotHaveAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found. Please use a different email..
        /// </summary>
        internal static string MessageAccountNotFoundByEmail {
            get {
                return ResourceManager.GetString("MessageAccountNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found. Please use a different phone number..
        /// </summary>
        internal static string MessageAccountNotFoundByPhone {
            get {
                return ResourceManager.GetString("MessageAccountNotFoundByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error. Account could not be restored to this state..
        /// </summary>
        internal static string MessageAccountRecoveryUnknownError {
            get {
                return ResourceManager.GetString("MessageAccountRecoveryUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to make sure you&apos;re not a robot!.
        /// </summary>
        internal static string MessageCaptchaError {
            get {
                return ResourceManager.GetString("MessageCaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words you typed didn&apos;t match the picture. Please try again..
        /// </summary>
        internal static string MessageCaptchaFailError {
            get {
                return ResourceManager.GetString("MessageCaptchaFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect. Please check them and try again..
        /// </summary>
        internal static string MessageCredentialsError {
            get {
                return ResourceManager.GetString("MessageCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a different password. Use any special characters or numbers..
        /// </summary>
        internal static string MessageDifferentPasswordComplex {
            get {
                return ResourceManager.GetString("MessageDifferentPasswordComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Please try again later..
        /// </summary>
        internal static string MessageFloodCheckedError {
            get {
                return ResourceManager.GetString("MessageFloodCheckedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature temporarily disabled. Please try again later..
        /// </summary>
        internal static string MessageForgotPasswordFeatureDisabled {
            get {
                return ResourceManager.GetString("MessageForgotPasswordFeatureDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email for login instructions.
        /// </summary>
        internal static string MessageForgotPasswordSuccess {
            get {
                return ResourceManager.GetString("MessageForgotPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status prevents resetting password.
        /// </summary>
        internal static string MessageInvalidAccountStatus {
            get {
                return ResourceManager.GetString("MessageInvalidAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string MessageInvalidPassword {
            get {
                return ResourceManager.GetString("MessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t load this security ticket..
        /// </summary>
        internal static string MessageInvalidTicket {
            get {
                return ResourceManager.GetString("MessageInvalidTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username, or no email exists.
        /// </summary>
        internal static string MessageInvalidUserNameOrEmail {
            get {
                return ResourceManager.GetString("MessageInvalidUserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileResetPasswordSuccess.
        /// </summary>
        internal static string MessageMobileResetPasswordSuccess {
            get {
                return ResourceManager.GetString("MessageMobileResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no accounts linked to this email address.
        /// </summary>
        internal static string MessageNoAccountsLinkedToEmail {
            get {
                return ResourceManager.GetString("MessageNoAccountsLinkedToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you are trying to log in with a username that has changed. Please log in with your new username..
        /// </summary>
        internal static string MessageOldUsernameError {
            get {
                return ResourceManager.GetString("MessageOldUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that password cannot be used..
        /// </summary>
        internal static string MessagePasswordCannotBeUsed {
            get {
                return ResourceManager.GetString("MessagePasswordCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, password reset requests expire {expirationHour} hours, {expirationMinute} minutes after issuance. Try requesting another password reset ticket again..
        /// </summary>
        internal static string MessagePasswordResetTicketExpired {
            get {
                return ResourceManager.GetString("MessagePasswordResetTicketExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your password reset link has expired. Please visit the {aTagStartWithHref}{forgotPasswordLinkUrl}{hrefEnd}Forgot Password page{aTagEnd} to receive a new link..
        /// </summary>
        internal static string MessagePasswordResetTicketExpiredWithLink {
            get {
                return ResourceManager.GetString("MessagePasswordResetTicketExpiredWithLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string MessagePasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("MessagePasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to Roblox to finish authenticating..
        /// </summary>
        internal static string MessageSamlUnauthenticated {
            get {
                return ResourceManager.GetString("MessageSamlUnauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string MessageUnknownError {
            get {
                return ResourceManager.GetString("MessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error. Please return to login screen..
        /// </summary>
        internal static string MessageUnknownSystemError {
            get {
                return ResourceManager.GetString("MessageUnknownSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code ({codeLength}-digit).
        /// </summary>
        internal static string Placeholder_EnterCode {
            get {
                return ResourceManager.GetString("Placeholder.EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Placeholder_PhoneNumber {
            get {
                return ResourceManager.GetString("Placeholder.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset success! Please login again..
        /// </summary>
        internal static string Response_PasswordResetSuccess {
            get {
                return ResourceManager.GetString("Response.PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Response_Success {
            get {
                return ResourceManager.GetString("Response.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Please try again later..
        /// </summary>
        internal static string Response_UpdatePasswordFlooded {
            get {
                return ResourceManager.GetString("Response.UpdatePasswordFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password is incorrect, the password was not changed..
        /// </summary>
        internal static string Response_UpdatePasswordIncorrect {
            get {
                return ResourceManager.GetString("Response.UpdatePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must include new password and confirm password.
        /// </summary>
        internal static string Response_UpdatePasswordInputMissing {
            get {
                return ResourceManager.GetString("Response.UpdatePasswordInputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password and confirm password must match.
        /// </summary>
        internal static string Response_UpdatePasswordMismatch {
            get {
                return ResourceManager.GetString("Response.UpdatePasswordMismatch", resourceCulture);
            }
        }
    }
}
