//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlertsAndOptionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertsAndOptionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common.AlertsAndOptionsResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_OK {
            get {
                return ResourceManager.GetString("Action.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Main Content.
        /// </summary>
        internal static string Action_SkipToMainContent {
            get {
                return ResourceManager.GetString("Action.SkipToMainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive experience use can interfere with normal daily life. You have visited on Roblox for {NumberOfHours} hour(s)..
        /// </summary>
        internal static string Description_KoreaScreentimeToastText_ {
            get {
                return ResourceManager.GetString("Description.KoreaScreentimeToastText\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Log In.
        /// </summary>
        internal static string Labels_sQuickLogInWeb {
            get {
                return ResourceManager.GetString("Labels.sQuickLogInWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a 13+ account..
        /// </summary>
        internal static string Label_OverThirteen {
            get {
                return ResourceManager.GetString("Label.OverThirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Robux.
        /// </summary>
        internal static string Label_sBuyRobux {
            get {
                return ResourceManager.GetString("Label.sBuyRobux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        internal static string Label_sFriendInvitations {
            get {
                return ResourceManager.GetString("Label.sFriendInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Friend Requests.
        /// </summary>
        internal static string Label_sFriendInvitationsMessage {
            get {
                return ResourceManager.GetString("Label.sFriendInvitationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Label_sHelp {
            get {
                return ResourceManager.GetString("Label.sHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Label_sLogout {
            get {
                return ResourceManager.GetString("Label.sLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Label_sMessages {
            get {
                return ResourceManager.GetString("Label.sMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Messages.
        /// </summary>
        internal static string Label_sMessagesMessage {
            get {
                return ResourceManager.GetString("Label.sMessagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Log In.
        /// </summary>
        internal static string Label_sQuickLogin {
            get {
                return ResourceManager.GetString("Label.sQuickLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robux.
        /// </summary>
        internal static string Label_sRobux {
            get {
                return ResourceManager.GetString("Label.sRobux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Â Robux.
        /// </summary>
        internal static string Label_sRobuxMessage {
            get {
                return ResourceManager.GetString("Label.sRobuxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Label_sSettings {
            get {
                return ResourceManager.GetString("Label.sSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Label_sTickets {
            get {
                return ResourceManager.GetString("Label.sTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tickets.
        /// </summary>
        internal static string Label_sTicketsMessage {
            get {
                return ResourceManager.GetString("Label.sTicketsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title.Warning", resourceCulture);
            }
        }
    }
}
