//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CommonUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonUI.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept All.
        /// </summary>
        internal static string Action_Accept {
            get {
                return ResourceManager.GetString("Action.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline All.
        /// </summary>
        internal static string Action_Decline {
            get {
                return ResourceManager.GetString("Action.Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_OK {
            get {
                return ResourceManager.GetString("Action.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Previous Page.
        /// </summary>
        internal static string Action_PreviousPage {
            get {
                return ResourceManager.GetString("Action.PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Home.
        /// </summary>
        internal static string Action_ReturnHome {
            get {
                return ResourceManager.GetString("Action.ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox uses cookies to personalize content, provide social media features and analyze the traffic on our site. To learn about how we use cookies and how you can {startLink}manage cookie preferences{endLink}, please refer to our {startLink2}Privacy and Cookie Policy{endLink2}..
        /// </summary>
        internal static string CookieLawNoticev2 {
            get {
                return ResourceManager.GetString("CookieLawNoticev2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue to receive this message, check out {startLink}our status{endLink}..
        /// </summary>
        internal static string Description_ErrorPageCheckStatus {
            get {
                return ResourceManager.GetString("Description.ErrorPageCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue to receive this page, please contact customer service at {0}..
        /// </summary>
        internal static string Description_ErrorPageLetUsKnow {
            get {
                return ResourceManager.GetString("Description.ErrorPageLetUsKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Image.
        /// </summary>
        internal static string Label_ErrorImage {
            get {
                return ResourceManager.GetString("Label.ErrorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters!.
        /// </summary>
        internal static string Label_TooManyCharacters {
            get {
                return ResourceManager.GetString("Label.TooManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigya.
        /// </summary>
        internal static string MessageEssentialCookiesItem3 {
            get {
                return ResourceManager.GetString("MessageEssentialCookiesItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always allowed.
        /// </summary>
        internal static string Message_AlwaysAllowed {
            get {
                return ResourceManager.GetString("Message.AlwaysAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics Cookies.
        /// </summary>
        internal static string Message_AnalyiticsCookies {
            get {
                return ResourceManager.GetString("Message.AnalyiticsCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These cookies used for improving site performance or understanding site usage..
        /// </summary>
        internal static string Message_AnalyiticsCookiesDescription {
            get {
                return ResourceManager.GetString("Message.AnalyiticsCookiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics.
        /// </summary>
        internal static string Message_AnalyiticsCookiesItem1 {
            get {
                return ResourceManager.GetString("Message.AnalyiticsCookiesItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Universal Analytics.
        /// </summary>
        internal static string Message_AnalyiticsCookiesItem2 {
            get {
                return ResourceManager.GetString("Message.AnalyiticsCookiesItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has been migrated to the Creator Dashboard. You can use the updated page by clicking..
        /// </summary>
        internal static string Message_CDRedirection {
            get {
                return ResourceManager.GetString("Message.CDRedirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [here].
        /// </summary>
        internal static string Message_CDRedirectionLinkText {
            get {
                return ResourceManager.GetString("Message.CDRedirectionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has been migrated to the Creator Dashboard. You can use the updated page by clicking {linkText}..
        /// </summary>
        internal static string Message_CDRedirectionMessage {
            get {
                return ResourceManager.GetString("Message.CDRedirectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox uses cookies to offer you a better experience. For further information, including information on how to withdraw consent and how to manage the use of cookies on Roblox, please refer to our {startLink}Privacy and Cookie Policy{endLink}..
        /// </summary>
        internal static string Message_CookieLawNotice {
            get {
                return ResourceManager.GetString("Message.CookieLawNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox uses cookies to personalize content, provide social media features and analyze the traffic on our site. To learn about how we use cookies and how you can {startLink}manage cookie preferences{endLink}, please refer to our {startLink2}Privacy and Cookie Policy{endLink2}..
        /// </summary>
        internal static string Message_CookieLawNoticev2 {
            get {
                return ResourceManager.GetString("Message.CookieLawNoticev2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose whether this site may use cookies as described below. You can learn more about how this site uses cookies and related technologies by reading our {startLink}privacy policy{endLink}..
        /// </summary>
        internal static string Message_CookieModalText {
            get {
                return ResourceManager.GetString("Message.CookieModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please check back in a few minutes..
        /// </summary>
        internal static string Message_ErrorGeneral {
            get {
                return ResourceManager.GetString("Message.ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential Cookies.
        /// </summary>
        internal static string Message_EssentialCookies {
            get {
                return ResourceManager.GetString("Message.EssentialCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These cookies are required to provide the functionality on the site, such as for user authentication, securing the system or saving cookie preferences..
        /// </summary>
        internal static string Message_EssentialCookiesDescription {
            get {
                return ResourceManager.GetString("Message.EssentialCookiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox.
        /// </summary>
        internal static string Message_EssentialCookiesItem1 {
            get {
                return ResourceManager.GetString("Message.EssentialCookiesItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zendesk.
        /// </summary>
        internal static string Message_EssentialCookiesItem2 {
            get {
                return ResourceManager.GetString("Message.EssentialCookiesItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cookies.
        /// </summary>
        internal static string Message_ManageCookies {
            get {
                return ResourceManager.GetString("Message.ManageCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is temporarily unavailable. Please try again later..
        /// </summary>
        internal static string Message_OperationUnavailable {
            get {
                return ResourceManager.GetString("Message.OperationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request size was over limit..
        /// </summary>
        internal static string Message_RequestSizeOverLimit {
            get {
                return ResourceManager.GetString("Message.RequestSizeOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text was moderated..
        /// </summary>
        internal static string Message_TextWasModerated {
            get {
                return ResourceManager.GetString("Message.TextWasModerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string Response_AccessDenied {
            get {
                return ResourceManager.GetString("Response.AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have permission to view this page!.
        /// </summary>
        internal static string Response_AccessDeniedDescription {
            get {
                return ResourceManager.GetString("Response.AccessDeniedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string Response_BadRequest {
            get {
                return ResourceManager.GetString("Response.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with your request.
        /// </summary>
        internal static string Response_BadRequestDescription {
            get {
                return ResourceManager.GetString("Response.BadRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error with your request.
        /// </summary>
        internal static string Response_InternalServerError {
            get {
                return ResourceManager.GetString("Response.InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again after a few moments..
        /// </summary>
        internal static string Response_InternalServerErrorDescription {
            get {
                return ResourceManager.GetString("Response.InternalServerErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested page not found.
        /// </summary>
        internal static string Response_PageNotFound {
            get {
                return ResourceManager.GetString("Response.PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have clicked an expired link or mistyped the address..
        /// </summary>
        internal static string Response_PageNotFoundDescription {
            get {
                return ResourceManager.GetString("Response.PageNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with your request.
        /// </summary>
        internal static string Response_RequestError {
            get {
                return ResourceManager.GetString("Response.RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Response_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Response.SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many Attempts.
        /// </summary>
        internal static string Response_TooManyAttemptsText {
            get {
                return ResourceManager.GetString("Response.TooManyAttemptsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        internal static string Response_UnexpectedError {
            get {
                return ResourceManager.GetString("Response.UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to use HTML characters such as &lt;b&gt; in forms on the website..
        /// </summary>
        internal static string Response_UnsafeInput {
            get {
                return ResourceManager.GetString("Response.UnsafeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsafe Input.
        /// </summary>
        internal static string Title_UnsafeInput {
            get {
                return ResourceManager.GetString("Title.UnsafeInput", resourceCulture);
            }
        }
    }
}
