//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CommonUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Features {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Features() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonUI.Features", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Premium.
        /// </summary>
        internal static string ActionsGetPremium {
            get {
                return ResourceManager.GetString("ActionsGetPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string ActionsPremium {
            get {
                return ResourceManager.GetString("ActionsPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Top.
        /// </summary>
        internal static string Action_BackToTop {
            get {
                return ResourceManager.GetString("Action.BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Access.
        /// </summary>
        internal static string Action_BuyAccess {
            get {
                return ResourceManager.GetString("Action.BuyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Now.
        /// </summary>
        internal static string Action_sUpgradeNow {
            get {
                return ResourceManager.GetString("Action.sUpgradeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to buy access to the Place: {placeName} from {creatorName} for {robux}?.
        /// </summary>
        internal static string BuyAccessToGameForModal {
            get {
                return ResourceManager.GetString("BuyAccessToGameForModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Â©2018 Roblox Corporation. Roblox, the Roblox logo and Powering Imagination are among our registered and unregistered trademarks in the U.S. and other countries..
        /// </summary>
        internal static string Description_CopyRightMessage {
            get {
                return ResourceManager.GetString("Description.CopyRightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Â©{copyrightYear} Roblox Corporation. Roblox, the Roblox logo and Powering Imagination are among our registered and unregistered trademarks in the U.S. and other countries..
        /// </summary>
        internal static string Description_CopyRightMessageDynamicYear {
            get {
                return ResourceManager.GetString("Description.CopyRightMessageDynamicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While some experiences may use the selected language, it is not fully supported by roblox.com..
        /// </summary>
        internal static string Description_UnsupportedLanguage {
            get {
                return ResourceManager.GetString("Description.UnsupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {userLanguage} is currently unavailable on roblox.com. You will see in-game content in {platformLanguage}, and roblox.com has been set to English..
        /// </summary>
        internal static string Description_UnsupportedLanguageModal {
            get {
                return ResourceManager.GetString("Description.UnsupportedLanguageModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Item.
        /// </summary>
        internal static string Heading_BuyItem {
            get {
                return ResourceManager.GetString("Heading.BuyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Private Server.
        /// </summary>
        internal static string Heading_ConfigurePrivateServer {
            get {
                return ResourceManager.GetString("Heading.ConfigurePrivateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Servers.
        /// </summary>
        internal static string Heading_PrivateServers {
            get {
                return ResourceManager.GetString("Heading.PrivateServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Language.
        /// </summary>
        internal static string Heading_UnsupportedLanguage {
            get {
                return ResourceManager.GetString("Heading.UnsupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string Label_AboutUs {
            get {
                return ResourceManager.GetString("Label.AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string Label_Accessibility {
            get {
                return ResourceManager.GetString("Label.Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Error.
        /// </summary>
        internal static string Label_AuthenticationError {
            get {
                return ResourceManager.GetString("Label.AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string Label_Avatar {
            get {
                return ResourceManager.GetString("Label.Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Shop.
        /// </summary>
        internal static string Label_AvatarShop {
            get {
                return ResourceManager.GetString("Label.AvatarShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string Label_Badges {
            get {
                return ResourceManager.GetString("Label.Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        internal static string Label_Careers {
            get {
                return ResourceManager.GetString("Label.Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Label_Configure {
            get {
                return ResourceManager.GetString("Label.Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Game.
        /// </summary>
        internal static string Label_ConfigureGame {
            get {
                return ResourceManager.GetString("Label.ConfigureGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Place.
        /// </summary>
        internal static string Label_ConfigurePlace {
            get {
                return ResourceManager.GetString("Label.ConfigurePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure VIP Server.
        /// </summary>
        internal static string Label_ConfigurePrivateServer {
            get {
                return ResourceManager.GetString("Label.ConfigurePrivateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string Label_ContactUs {
            get {
                return ResourceManager.GetString("Label.ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Label_Create {
            get {
                return ResourceManager.GetString("Label.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        internal static string Label_CreateGame {
            get {
                return ResourceManager.GetString("Label.CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        internal static string Label_CreateGroup {
            get {
                return ResourceManager.GetString("Label.CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Ad.
        /// </summary>
        internal static string Label_CreateUserAd {
            get {
                return ResourceManager.GetString("Label.CreateUserAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string Label_Discover {
            get {
                return ResourceManager.GetString("Label.Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        internal static string Label_Experience {
            get {
                return ResourceManager.GetString("Label.Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Label_Favorites {
            get {
                return ResourceManager.GetString("Label.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Feed.
        /// </summary>
        internal static string Label_Feeds {
            get {
                return ResourceManager.GetString("Label.Feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Cards.
        /// </summary>
        internal static string Label_GiftCards {
            get {
                return ResourceManager.GetString("Label.GiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Label_Help {
            get {
                return ResourceManager.GetString("Label.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Label_Jobs {
            get {
                return ResourceManager.GetString("Label.Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Label_Library {
            get {
                return ResourceManager.GetString("Label.Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandise.
        /// </summary>
        internal static string Label_Merch {
            get {
                return ResourceManager.GetString("Label.Merch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transactions.
        /// </summary>
        internal static string Label_MyMoney {
            get {
                return ResourceManager.GetString("Label.MyMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Store.
        /// </summary>
        internal static string Label_OfficialStore {
            get {
                return ResourceManager.GetString("Label.OfficialStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string Label_Parents {
            get {
                return ResourceManager.GetString("Label.Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Statistics.
        /// </summary>
        internal static string Label_PlaceStatistics {
            get {
                return ResourceManager.GetString("Label.PlaceStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string Label_Players {
            get {
                return ResourceManager.GetString("Label.Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Label_Privacy {
            get {
                return ResourceManager.GetString("Label.Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Name Verified.
        /// </summary>
        internal static string Label_RealNameVerified {
            get {
                return ResourceManager.GetString("Label.RealNameVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Roblox Cards.
        /// </summary>
        internal static string Label_RedeemRobloxCards {
            get {
                return ResourceManager.GetString("Label.RedeemRobloxCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string Label_sAvatar {
            get {
                return ResourceManager.GetString("Label.sAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Label_sBlog {
            get {
                return ResourceManager.GetString("Label.sBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Label_sBrowse {
            get {
                return ResourceManager.GetString("Label.sBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builders Club.
        /// </summary>
        internal static string Label_sBuildersClub {
            get {
                return ResourceManager.GetString("Label.sBuildersClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string Label_sCatalog {
            get {
                return ResourceManager.GetString("Label.sCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop.
        /// </summary>
        internal static string Label_sDevelop {
            get {
                return ResourceManager.GetString("Label.sDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Label_sEvents {
            get {
                return ResourceManager.GetString("Label.sEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Label_sForum {
            get {
                return ResourceManager.GetString("Label.sForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Label_sFriends {
            get {
                return ResourceManager.GetString("Label.sFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Label_sGames {
            get {
                return ResourceManager.GetString("Label.sGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Label_sGroups {
            get {
                return ResourceManager.GetString("Label.sGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Label_sHome {
            get {
                return ResourceManager.GetString("Label.sHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Label_sInventory {
            get {
                return ResourceManager.GetString("Label.sInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards.
        /// </summary>
        internal static string Label_sLeaderboards {
            get {
                return ResourceManager.GetString("Label.sLeaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_sLogin {
            get {
                return ResourceManager.GetString("Label.sLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Label_sMessages {
            get {
                return ResourceManager.GetString("Label.sMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Label_sMore {
            get {
                return ResourceManager.GetString("Label.sMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Label_sOr {
            get {
                return ResourceManager.GetString("Label.sOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string Label_sPeople {
            get {
                return ResourceManager.GetString("Label.sPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Label_sProfile {
            get {
                return ResourceManager.GetString("Label.sProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robux.
        /// </summary>
        internal static string Label_sRobux {
            get {
                return ResourceManager.GetString("Label.sRobux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_sSearch {
            get {
                return ResourceManager.GetString("Label.sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search \&quot;{phrase}\&quot; in {location}.
        /// </summary>
        internal static string Label_sSearchPhrase {
            get {
                return ResourceManager.GetString("Label.sSearchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {location}.
        /// </summary>
        internal static string Label_sSearchPhraseV2 {
            get {
                return ResourceManager.GetString("Label.sSearchPhraseV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string Label_sShop {
            get {
                return ResourceManager.GetString("Label.sShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Label_sSignUp {
            get {
                return ResourceManager.GetString("Label.sSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Label_Store {
            get {
                return ResourceManager.GetString("Label.Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string Label_sTrade {
            get {
                return ResourceManager.GetString("Label.sTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Label_Support {
            get {
                return ResourceManager.GetString("Label.Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string Label_Terms {
            get {
                return ResourceManager.GetString("Label.Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string Label_TermsOfUse {
            get {
                return ResourceManager.GetString("Label.TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string Label_Thanks {
            get {
                return ResourceManager.GetString("Label.Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string Label_Upgrade {
            get {
                return ResourceManager.GetString("Label.Upgrade", resourceCulture);
            }
        }
    }
}
