//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CommonUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonUI.Controls", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Action_Accept {
            get {
                return ResourceManager.GetString("Action.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept All.
        /// </summary>
        internal static string Action_AcceptAll {
            get {
                return ResourceManager.GetString("Action.AcceptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Action_Agree {
            get {
                return ResourceManager.GetString("Action.Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string Action_Allow {
            get {
                return ResourceManager.GetString("Action.Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Action_Back {
            get {
                return ResourceManager.GetString("Action.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Robux.
        /// </summary>
        internal static string Action_BuyRobux {
            get {
                return ResourceManager.GetString("Action.BuyRobux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string Action_Collapse {
            get {
                return ResourceManager.GetString("Action.Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Action_Confirm {
            get {
                return ResourceManager.GetString("Action.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Action_Continue {
            get {
                return ResourceManager.GetString("Action.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Action_Decline {
            get {
                return ResourceManager.GetString("Action.Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline All.
        /// </summary>
        internal static string Action_DeclineAll {
            get {
                return ResourceManager.GetString("Action.DeclineAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Action_Delete {
            get {
                return ResourceManager.GetString("Action.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Action_Disable {
            get {
                return ResourceManager.GetString("Action.Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string Action_Discard {
            get {
                return ResourceManager.GetString("Action.Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute.
        /// </summary>
        internal static string Action_Distribute {
            get {
                return ResourceManager.GetString("Action.Distribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Action_Enable {
            get {
                return ResourceManager.GetString("Action.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string Action_IgnoreAll {
            get {
                return ResourceManager.GetString("Action.IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Action_Next {
            get {
                return ResourceManager.GetString("Action.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Action_No {
            get {
                return ResourceManager.GetString("Action.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_OK {
            get {
                return ResourceManager.GetString("Action.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Action_Remove {
            get {
                return ResourceManager.GetString("Action.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Action_Save {
            get {
                return ResourceManager.GetString("Action.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Action_Search {
            get {
                return ResourceManager.GetString("Action.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        internal static string Action_SeeAll {
            get {
                return ResourceManager.GetString("Action.SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Less.
        /// </summary>
        internal static string Action_SeeLess {
            get {
                return ResourceManager.GetString("Action.SeeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        internal static string Action_SeeMore {
            get {
                return ResourceManager.GetString("Action.SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Action_Show {
            get {
                return ResourceManager.GetString("Action.Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Action_Stop {
            get {
                return ResourceManager.GetString("Action.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Action_Submit {
            get {
                return ResourceManager.GetString("Action.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Action_Yes {
            get {
                return ResourceManager.GetString("Action.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Birthdaypicker_Label_Date {
            get {
                return ResourceManager.GetString("Birthdaypicker.Label.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you want to proceed?.
        /// </summary>
        internal static string Description_UnsavedChange {
            get {
                return ResourceManager.GetString("Description.UnsavedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Label_April {
            get {
                return ResourceManager.GetString("Label.April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        internal static string Label_AprilAbbreviated {
            get {
                return ResourceManager.GetString("Label.AprilAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Label_August {
            get {
                return ResourceManager.GetString("Label.August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        internal static string Label_AugustAbbreviated {
            get {
                return ResourceManager.GetString("Label.AugustAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string Label_CurrentPage {
            get {
                return ResourceManager.GetString("Label.CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Label_Day {
            get {
                return ResourceManager.GetString("Label.Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Label_December {
            get {
                return ResourceManager.GetString("Label.December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string Label_DecemberAbbreviated {
            get {
                return ResourceManager.GetString("Label.DecemberAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Label_February {
            get {
                return ResourceManager.GetString("Label.February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string Label_FebruaryAbbreviated {
            get {
                return ResourceManager.GetString("Label.FebruaryAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Label_January {
            get {
                return ResourceManager.GetString("Label.January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string Label_JanuaryAbbreviated {
            get {
                return ResourceManager.GetString("Label.JanuaryAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Label_July {
            get {
                return ResourceManager.GetString("Label.July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Label_June {
            get {
                return ResourceManager.GetString("Label.June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Label_March {
            get {
                return ResourceManager.GetString("Label.March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string Label_MarchAbbreviated {
            get {
                return ResourceManager.GetString("Label.MarchAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Label_May {
            get {
                return ResourceManager.GetString("Label.May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Label_Month {
            get {
                return ResourceManager.GetString("Label.Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Label_Next {
            get {
                return ResourceManager.GetString("Label.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Label_November {
            get {
                return ResourceManager.GetString("Label.November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string Label_NovemberAbbreviated {
            get {
                return ResourceManager.GetString("Label.NovemberAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Label_October {
            get {
                return ResourceManager.GetString("Label.October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string Label_OctoberAbbreviated {
            get {
                return ResourceManager.GetString("Label.OctoberAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Label_Previous {
            get {
                return ResourceManager.GetString("Label.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Label_September {
            get {
                return ResourceManager.GetString("Label.September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept.
        /// </summary>
        internal static string Label_SeptemberAbbreviated {
            get {
                return ResourceManager.GetString("Label.SeptemberAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Label_Summary {
            get {
                return ResourceManager.GetString("Label.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string Label_UnsavedChanges {
            get {
                return ResourceManager.GetString("Label.UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Label_Week {
            get {
                return ResourceManager.GetString("Label.Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Label_Year {
            get {
                return ResourceManager.GetString("Label.Year", resourceCulture);
            }
        }
    }
}
