//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VisitGame {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisitGame() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common.VisitGame", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} This game may perform poorly on your device..
        /// </summary>
        internal static string Action_GamePerformPoorly {
            get {
                return ResourceManager.GetString("Action.GamePerformPoorly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Action_Retry {
            get {
                return ResourceManager.GetString("Action.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting game.
        /// </summary>
        internal static string Heading_ErrorStartingGame {
            get {
                return ResourceManager.GetString("Heading.ErrorStartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Desktop Mode to Play Games.
        /// </summary>
        internal static string Heading_SwitchToDesktopToPlay {
            get {
                return ResourceManager.GetString("Heading.SwitchToDesktopToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Access for {0} Robux.
        /// </summary>
        internal static string Label_BuyAccess {
            get {
                return ResourceManager.GetString("Label.BuyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Roblox Studio....
        /// </summary>
        internal static string Label_CheckingForStudio {
            get {
                return ResourceManager.GetString("Label.CheckingForStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for help.
        /// </summary>
        internal static string Label_ClickHereForHelp {
            get {
                return ResourceManager.GetString("Label.ClickHereForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Players....
        /// </summary>
        internal static string Label_ConnectingToPlayers {
            get {
                return ResourceManager.GetString("Label.ConnectingToPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop.
        /// </summary>
        internal static string Label_DevelopPageTitle {
            get {
                return ResourceManager.GetString("Label.DevelopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Install Roblox.
        /// </summary>
        internal static string Label_DownloadInstallRoblox {
            get {
                return ResourceManager.GetString("Label.DownloadInstallRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Studio.
        /// </summary>
        internal static string Label_DownloadStudio {
            get {
                return ResourceManager.GetString("Label.DownloadStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Configure.
        /// </summary>
        internal static string Label_GameConfigurePageTitle {
            get {
                return ResourceManager.GetString("Label.GameConfigurePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free because you are a soothsayer.
        /// </summary>
        internal static string Label_GameFreeSoothsayer {
            get {
                return ResourceManager.GetString("Label.GameFreeSoothsayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only developers can visit because this game is private. Make it public on the {0}Configure Game{1} page..
        /// </summary>
        internal static string Label_GameIsPrivatePlayableByGroupOnly {
            get {
                return ResourceManager.GetString("Label.GameIsPrivatePlayableByGroupOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only you can visit because this game is private. Make it public on the {0}Configure game{1} page..
        /// </summary>
        internal static string Label_GameIsPrivatePlayableByOwnerOnly {
            get {
                return ResourceManager.GetString("Label.GameIsPrivatePlayableByOwnerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is private, but you can visit because you&apos;re a tester..
        /// </summary>
        internal static string Label_GameIsPrivatePlayableByPlaytester {
            get {
                return ResourceManager.GetString("Label.GameIsPrivatePlayableByPlaytester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is unavailable due to account restrictions settings..
        /// </summary>
        internal static string Label_GameUnavailableAccountResrictions {
            get {
                return ResourceManager.GetString("Label.GameUnavailableAccountResrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot visit games from Studio. Please use a web browser to visit this game..
        /// </summary>
        internal static string Label_GameUnavailableCannotPlayGamesStudio {
            get {
                return ResourceManager.GetString("Label.GameUnavailableCannotPlayGamesStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this place is currently closed to visitors..
        /// </summary>
        internal static string Label_GameUnavailableClosedToVisitors {
            get {
                return ResourceManager.GetString("Label.GameUnavailableClosedToVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only developers can visit because this game is private. Make it public on the {0}Develop{1} page..
        /// </summary>
        internal static string Label_GameUnavailableCurrentlyIsPrivateGroup {
            get {
                return ResourceManager.GetString("Label.GameUnavailableCurrentlyIsPrivateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only you can visit because this game is private. Make it public on the {0}Develop{1} page..
        /// </summary>
        internal static string Label_GameUnavailableCurrentlyIsPrivateOwner {
            get {
                return ResourceManager.GetString("Label.GameUnavailableCurrentlyIsPrivateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this game is private..
        /// </summary>
        internal static string Label_GameUnavailableCurrentlyIsPrivateVisitor {
            get {
                return ResourceManager.GetString("Label.GameUnavailableCurrentlyIsPrivateVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is currently private. Make it public on the {1} page to make it available..
        /// </summary>
        internal static string Label_GameUnavailableCurrentlyPrivate {
            get {
                return ResourceManager.GetString("Label.GameUnavailableCurrentlyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your account is restricted from visiting Experimental Games unless you are friends with the creator..
        /// </summary>
        internal static string Label_GameUnavailableGameInsecure {
            get {
                return ResourceManager.GetString("Label.GameUnavailableGameInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This place is part of a game that has no root place. Add a root place on the {0} page to make it available..
        /// </summary>
        internal static string Label_GameUnavailableNoRootPlace {
            get {
                return ResourceManager.GetString("Label.GameUnavailableNoRootPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission levels on this place prevent you from entering..
        /// </summary>
        internal static string Label_GameUnavailablePermissionLevels {
            get {
                return ResourceManager.GetString("Label.GameUnavailablePermissionLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This place is not currently part of a Game. Add it to a game on the {0} page to make it available..
        /// </summary>
        internal static string Label_GameUnavailablePlaceNotPartOfGame {
            get {
                return ResourceManager.GetString("Label.GameUnavailablePlaceNotPartOfGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this place is currently under review. Try again later..
        /// </summary>
        internal static string Label_GameUnavailablePlaceUnderReview {
            get {
                return ResourceManager.GetString("Label.GameUnavailablePlaceUnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is not available on your platform.  Check the game page to see all available games..
        /// </summary>
        internal static string Label_GameUnavailablePlatform {
            get {
                return ResourceManager.GetString("Label.GameUnavailablePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is unavailable because its starting place is unpublished. Publish the starting place to make it available..
        /// </summary>
        internal static string Label_GameUnavailableRootPlaceIsUnpublished {
            get {
                return ResourceManager.GetString("Label.GameUnavailableRootPlaceIsUnpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Label_GameWarning {
            get {
                return ResourceManager.GetString("Label.GameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Instructions.
        /// </summary>
        internal static string Label_InstallationInstructions {
            get {
                return ResourceManager.GetString("Label.InstallationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Application.
        /// </summary>
        internal static string Label_LaunchApplication {
            get {
                return ResourceManager.GetString("Label.LaunchApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) A window will open. Click {0}Open{1}.{2}2) Doubleclick the Roblox icon..
        /// </summary>
        internal static string Label_OperaInstallSteps {
            get {
                return ResourceManager.GetString("Label.OperaInstallSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started creating your own games!.
        /// </summary>
        internal static string Label_PersuadeToDevelopRoblox {
            get {
                return ResourceManager.GetString("Label.PersuadeToDevelopRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re moments away from getting into the game!.
        /// </summary>
        internal static string Label_PersuadeToInstallRoblox {
            get {
                return ResourceManager.GetString("Label.PersuadeToInstallRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Label_Play {
            get {
                return ResourceManager.GetString("Label.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit in App.
        /// </summary>
        internal static string Label_PlayInApp {
            get {
                return ResourceManager.GetString("Label.PlayInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox is now loading. Get ready!.
        /// </summary>
        internal static string Label_RobloxLoadingToPlay {
            get {
                return ResourceManager.GetString("Label.RobloxLoadingToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Roblox....
        /// </summary>
        internal static string Label_StartingRoblox {
            get {
                return ResourceManager.GetString("Label.StartingRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Desktop Mode.
        /// </summary>
        internal static string Label_SwitchToDesktopMode {
            get {
                return ResourceManager.GetString("Label.SwitchToDesktopMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universe Configuration.
        /// </summary>
        internal static string Label_UniverseConfigurePageTitle {
            get {
                return ResourceManager.GetString("Label.UniverseConfigurePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having trouble installing ROBLOX?.
        /// </summary>
        internal static string ResponseDialogHavingTroubleInstallQuestion {
            get {
                return ResourceManager.GetString("ResponseDialogHavingTroubleInstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}Always open links for Roblox{1} and click {2}Open Roblox{3} in the dialog box above to visit games faster in the future!.
        /// </summary>
        internal static string Response_CheckAlwaysOpenRoblox {
            get {
                return ResourceManager.GetString("Response.CheckAlwaysOpenRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}Always open links for URL: Roblox Protocol{1} and click {2}Open URL: Roblox Protocol{3} in the dialog box above to join games faster in the future!.
        /// </summary>
        internal static string Response_CheckAlwaysOpenRobloxURL {
            get {
                return ResourceManager.GetString("Response.CheckAlwaysOpenRobloxURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}Remember my choice{1} and click {2}OK{3} in the dialog box above to join games faster in the future!.
        /// </summary>
        internal static string Response_CheckRememberMyChoiceOK {
            get {
                return ResourceManager.GetString("Response.CheckRememberMyChoiceOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here!.
        /// </summary>
        internal static string Response_Dialog_ClickHere {
            get {
                return ResourceManager.GetString("Response.Dialog.ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to launch the game.  Please try again later..
        /// </summary>
        internal static string Response_Dialog_ErrorLaunching {
            get {
                return ResourceManager.GetString("Response.Dialog.ErrorLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having trouble installing Roblox?.
        /// </summary>
        internal static string Response_Dialog_HavingTroubleInstallQuestion {
            get {
                return ResourceManager.GetString("Response.Dialog.HavingTroubleInstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Roblox installer should download shortly. If it doesn&apos;t, start the {0}download now.{1}.
        /// </summary>
        internal static string Response_Dialog_InstallingMessageWithLink {
            get {
                return ResourceManager.GetString("Response.Dialog.InstallingMessageWithLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After installation, click {0}Join{1} below to join the action!.
        /// </summary>
        internal static string Response_Dialog_MacChromeFifthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacChromeFifthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Roblox.dmg{1} to run the Roblox installer, which just downloaded via your web browser..
        /// </summary>
        internal static string Response_Dialog_MacChromeFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacChromeFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Ok{1} once you&apos;ve successfully installed Roblox..
        /// </summary>
        internal static string Response_Dialog_MacChromeFourthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacChromeFourthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click the Roblox app icon to begin the installation process..
        /// </summary>
        internal static string Response_Dialog_MacChromeSecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacChromeSecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Open{1} when prompted by your computer..
        /// </summary>
        internal static string Response_Dialog_MacChromeThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacChromeThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then select the {0}Remember my choice...{1} checkbox and click {2}OK{3}.
        /// </summary>
        internal static string Response_Dialog_MacFirefoxFifthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacFirefoxFifthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0}Open with{1} and click {2}OK{3}.
        /// </summary>
        internal static string Response_Dialog_MacFirefoxFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacFirefoxFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once installed, click {0}Join{1} to join the action!.
        /// </summary>
        internal static string Response_Dialog_MacFirefoxFourthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacFirefoxFourthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click the {0}Roblox Icon{1} to begin the installation process.
        /// </summary>
        internal static string Response_Dialog_MacFirefoxSecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacFirefoxSecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a warning, click {0}Open{1}.
        /// </summary>
        internal static string Response_Dialog_MacFirefoxThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacFirefoxThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Downloads and double-click {0}Roblox.dmg{1}.
        /// </summary>
        internal static string Response_Dialog_MacSafariFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacSafariFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once installed, click {0}Join{1} to join the action!.
        /// </summary>
        internal static string Response_Dialog_MacSafariFourthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacSafariFourthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click the {0}Roblox Icon{1} to begin the installation process.
        /// </summary>
        internal static string Response_Dialog_MacSafariSecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacSafariSecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a warning, click {0}Open{1}.
        /// </summary>
        internal static string Response_Dialog_MacSafariThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.MacSafariThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}RobloxPlayer.exe{1} to run the Roblox installer, which just downloaded via your web browser..
        /// </summary>
        internal static string Response_Dialog_PcChromeFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcChromeFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After installation, click {0}Join{1} below to join the action!.
        /// </summary>
        internal static string Response_Dialog_PcChromeFourthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcChromeFourthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Run{1} when prompted by your computer to begin the installation process..
        /// </summary>
        internal static string Response_Dialog_PcChromeSecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcChromeSecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Ok{1} once you&apos;ve successfully installed Roblox..
        /// </summary>
        internal static string Response_Dialog_PcChromeThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcChromeThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Run{1} to install Roblox after the download finishes.
        /// </summary>
        internal static string Response_Dialog_PcEdgeFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcEdgeFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Ok{1} to finish installing Roblox.
        /// </summary>
        internal static string Response_Dialog_PcEdgeSecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcEdgeSecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the {0}Join{1} button to join the action!.
        /// </summary>
        internal static string Response_Dialog_PcEdgeThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcEdgeThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Ok{1} when the alert pops up.
        /// </summary>
        internal static string Response_Dialog_PcFirefoxFifthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcFirefoxFifthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Save File{1} when the download window pops up.
        /// </summary>
        internal static string Response_Dialog_PcFirefoxFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcFirefoxFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once installed, click {0}Join{1} to join the action!.
        /// </summary>
        internal static string Response_Dialog_PcFirefoxFourthInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcFirefoxFourthInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Downloads and double click {0}RobloxPlayer.exe{1}.
        /// </summary>
        internal static string Response_Dialog_PcFirefoxSecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcFirefoxSecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Run{1}.
        /// </summary>
        internal static string Response_Dialog_PcFirefoxThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcFirefoxThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a warning, click {0}Run{1}.
        /// </summary>
        internal static string Response_Dialog_PcIEFirstInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcIEFirstInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a warning, click {0}Run{1}.
        /// </summary>
        internal static string Response_Dialog_PcIeInstructionOne {
            get {
                return ResourceManager.GetString("Response.Dialog.PcIeInstructionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Run{1}.
        /// </summary>
        internal static string Response_Dialog_PcIeInstructionThree {
            get {
                return ResourceManager.GetString("Response.Dialog.PcIeInstructionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Downloads and double click {0}RobloxPlayer.exe{1}.
        /// </summary>
        internal static string Response_Dialog_PcIeInstructionTwo {
            get {
                return ResourceManager.GetString("Response.Dialog.PcIeInstructionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click {0}Ok{1} once you&apos;ve installed Roblox.
        /// </summary>
        internal static string Response_Dialog_PcIESecondInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcIESecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once installed, click {0}Join{1} to join the action!.
        /// </summary>
        internal static string Response_Dialog_PcIEThirdInstruction {
            get {
                return ResourceManager.GetString("Response.Dialog.PcIEThirdInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for visiting Roblox.
        /// </summary>
        internal static string Response_Dialog_ThanksForPlayingRoblox {
            get {
                return ResourceManager.GetString("Response.Dialog.ThanksForPlayingRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify that you have access to this game.  Please try again later..
        /// </summary>
        internal static string Response_GameTemporarilyUnavailable {
            get {
                return ResourceManager.GetString("Response.GameTemporarilyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}Remember my choice{1} and click {2} in the dialog box above to join games faster in the future!.
        /// </summary>
        internal static string Response_RememberMyChoiceAppLaunch {
            get {
                return ResourceManager.GetString("Response.RememberMyChoiceAppLaunch", resourceCulture);
            }
        }
    }
}
