//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Feature {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Feature.Profile", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Options.
        /// </summary>
        internal static string ActionFriendOptions {
            get {
                return ResourceManager.GetString("ActionFriendOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Request Pending.
        /// </summary>
        internal static string ActionFriendRequestPending {
            get {
                return ResourceManager.GetString("ActionFriendRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite To Party.
        /// </summary>
        internal static string ActionInviteToParty {
            get {
                return ResourceManager.GetString("ActionInviteToParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        internal static string ActionJoinGame {
            get {
                return ResourceManager.GetString("ActionJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Best Friend.
        /// </summary>
        internal static string ActionMakeTopFriend {
            get {
                return ResourceManager.GetString("ActionMakeTopFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Best Friend.
        /// </summary>
        internal static string ActionRemoveTopFriend {
            get {
                return ResourceManager.GetString("ActionRemoveTopFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        internal static string ActionSendFriendInvitation {
            get {
                return ResourceManager.GetString("ActionSendFriendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string ActionSendMessage {
            get {
                return ResourceManager.GetString("ActionSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Chatting.
        /// </summary>
        internal static string ActionStartChatting {
            get {
                return ResourceManager.GetString("ActionStartChatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Public Profile.
        /// </summary>
        internal static string ActionViewPublicProfile {
            get {
                return ResourceManager.GetString("ActionViewPublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Action_Accept {
            get {
                return ResourceManager.GetString("Action.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        internal static string Action_AddFriend {
            get {
                return ResourceManager.GetString("Action.AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User.
        /// </summary>
        internal static string Action_BlockUser {
            get {
                return ResourceManager.GetString("Action.BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_CancelBlockUser {
            get {
                return ResourceManager.GetString("Action.CancelBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Action_Chat {
            get {
                return ResourceManager.GetString("Action.Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Action_Close {
            get {
                return ResourceManager.GetString("Action.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Action_ConfirmBlockUser {
            get {
                return ResourceManager.GetString("Action.ConfirmBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string Action_ConfirmUnblockUser {
            get {
                return ResourceManager.GetString("Action.ConfirmUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Action_Favorites {
            get {
                return ResourceManager.GetString("Action.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Action_Follow {
            get {
                return ResourceManager.GetString("Action.Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        internal static string Action_GridView {
            get {
                return ResourceManager.GetString("Action.GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonate User.
        /// </summary>
        internal static string Action_ImpersonateUser {
            get {
                return ResourceManager.GetString("Action.ImpersonateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Action_Inventory {
            get {
                return ResourceManager.GetString("Action.Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Action_JoinGame {
            get {
                return ResourceManager.GetString("Action.JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Action_Message {
            get {
                return ResourceManager.GetString("Action.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Action_Pending {
            get {
                return ResourceManager.GetString("Action.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Action_Save {
            get {
                return ResourceManager.GetString("Action.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        internal static string Action_SeeAll {
            get {
                return ResourceManager.GetString("Action.SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Less.
        /// </summary>
        internal static string Action_SeeLess {
            get {
                return ResourceManager.GetString("Action.SeeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        internal static string Action_SeeMore {
            get {
                return ResourceManager.GetString("Action.SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow View.
        /// </summary>
        internal static string Action_SlideshowView {
            get {
                return ResourceManager.GetString("Action.SlideshowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string Action_Trade {
            get {
                return ResourceManager.GetString("Action.Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Items.
        /// </summary>
        internal static string Action_TradeItems {
            get {
                return ResourceManager.GetString("Action.TradeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock User.
        /// </summary>
        internal static string Action_UnblockUser {
            get {
                return ResourceManager.GetString("Action.UnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string Action_Unfollow {
            get {
                return ResourceManager.GetString("Action.Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriend.
        /// </summary>
        internal static string Action_Unfriend {
            get {
                return ResourceManager.GetString("Action.Unfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        internal static string Action_UpdateStatus {
            get {
                return ResourceManager.GetString("Action.UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has changed usernames..
        /// </summary>
        internal static string DescriptionChangedUsernames {
            get {
                return ResourceManager.GetString("DescriptionChangedUsernames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated description..
        /// </summary>
        internal static string Description_AboutSuccess {
            get {
                return ResourceManager.GetString("Description.AboutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep yourself safe, do not share personal details online..
        /// </summary>
        internal static string Description_AboutWarning {
            get {
                return ResourceManager.GetString("Description.AboutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;ve blocked a user, neither of you can directly contact the other..
        /// </summary>
        internal static string Description_BlockUserFooter {
            get {
                return ResourceManager.GetString("Description.BlockUserFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block this user?.
        /// </summary>
        internal static string Description_BlockUserPrompt {
            get {
                return ResourceManager.GetString("Description.BlockUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only you can see this information.
        /// </summary>
        internal static string Description_ChangeAlias {
            get {
                return ResourceManager.GetString("Description.ChangeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update description, please try again later..
        /// </summary>
        internal static string Description_Error {
            get {
                return ResourceManager.GetString("Description.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell the Roblox community about what you like to make, build, and explore....
        /// </summary>
        internal static string Description_PlaceholderStatus {
            get {
                return ResourceManager.GetString("Description.PlaceholderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unblock this user?.
        /// </summary>
        internal static string Description_UnblockUserPrompt {
            get {
                return ResourceManager.GetString("Description.UnblockUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Badges.
        /// </summary>
        internal static string HeadingPlayerBadge {
            get {
                return ResourceManager.GetString("HeadingPlayerBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROBLOX Badges.
        /// </summary>
        internal static string HeadingRobloxBadges {
            get {
                return ResourceManager.GetString("HeadingRobloxBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Sets.
        /// </summary>
        internal static string HeadingSets {
            get {
                return ResourceManager.GetString("HeadingSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Places.
        /// </summary>
        internal static string HeadingShowcase {
            get {
                return ResourceManager.GetString("HeadingShowcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Profile.
        /// </summary>
        internal static string HeadingUsersProfile {
            get {
                return ResourceManager.GetString("HeadingUsersProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        internal static string HeadingYourProfile {
            get {
                return ResourceManager.GetString("HeadingYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Heading_AboutTab {
            get {
                return ResourceManager.GetString("Heading.AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Heading_BlockUserTitle {
            get {
                return ResourceManager.GetString("Heading.BlockUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        internal static string Heading_Collections {
            get {
                return ResourceManager.GetString("Heading.Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Wearing.
        /// </summary>
        internal static string Heading_CurrentlyWearing {
            get {
                return ResourceManager.GetString("Heading.CurrentlyWearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Heading_FavoriteGames {
            get {
                return ResourceManager.GetString("Heading.FavoriteGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Heading_Friends {
            get {
                return ResourceManager.GetString("Heading.Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends ({0}).
        /// </summary>
        internal static string Heading_FriendsNum {
            get {
                return ResourceManager.GetString("Heading.FriendsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Heading_Games {
            get {
                return ResourceManager.GetString("Heading.Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Heading_GameTitle {
            get {
                return ResourceManager.GetString("Heading.GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Heading_Groups {
            get {
                return ResourceManager.GetString("Heading.Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string Heading_PlayerAssetsBadges {
            get {
                return ResourceManager.GetString("Heading.PlayerAssetsBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        internal static string Heading_PlayerAssetsClothing {
            get {
                return ResourceManager.GetString("Heading.PlayerAssetsClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string Heading_PlayerAssetsModels {
            get {
                return ResourceManager.GetString("Heading.PlayerAssetsModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string Heading_PlayerBadge {
            get {
                return ResourceManager.GetString("Heading.PlayerBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Heading_Profile {
            get {
                return ResourceManager.GetString("Heading.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Heading_ProfileGroups {
            get {
                return ResourceManager.GetString("Heading.ProfileGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox Badges.
        /// </summary>
        internal static string Heading_RobloxBadge {
            get {
                return ResourceManager.GetString("Heading.RobloxBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Heading_Statistics {
            get {
                return ResourceManager.GetString("Heading.Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan Points.
        /// </summary>
        internal static string LabelClanPoints {
            get {
                return ResourceManager.GetString("LabelClanPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {0}.
        /// </summary>
        internal static string LabelGreeting {
            get {
                return ResourceManager.GetString("LabelGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string LabelOffline {
            get {
                return ResourceManager.GetString("LabelOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string LabelOnline {
            get {
                return ResourceManager.GetString("LabelOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {0} ].
        /// </summary>
        internal static string LabelOnlineStatus {
            get {
                return ResourceManager.GetString("LabelOnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {0}: &lt;span class=\&quot;notranslate\&quot;&gt;{1}&lt;/span&gt; ].
        /// </summary>
        internal static string LabelOnlineStatusDetailed {
            get {
                return ResourceManager.GetString("LabelOnlineStatusDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Group.
        /// </summary>
        internal static string LabelPrimaryGroup {
            get {
                return ResourceManager.GetString("LabelPrimaryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Points.
        /// </summary>
        internal static string LabelUserPoints {
            get {
                return ResourceManager.GetString("LabelUserPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Label_About {
            get {
                return ResourceManager.GetString("Label.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Label_Alias {
            get {
                return ResourceManager.GetString("Label.Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block this user?.
        /// </summary>
        internal static string Label_BlockWarningBody {
            get {
                return ResourceManager.GetString("Label.BlockWarningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Label_BlockWarningConfirm {
            get {
                return ResourceManager.GetString("Label.BlockWarningConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;ve blocked a user, neither of you can directly contact the other..
        /// </summary>
        internal static string Label_BlockWarningFooter {
            get {
                return ResourceManager.GetString("Label.BlockWarningFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Alias.
        /// </summary>
        internal static string Label_ChangeAlias {
            get {
                return ResourceManager.GetString("Label.ChangeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creations.
        /// </summary>
        internal static string Label_Creations {
            get {
                return ResourceManager.GetString("Label.Creations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string Label_Followers {
            get {
                return ResourceManager.GetString("Label.Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Label_Following {
            get {
                return ResourceManager.GetString("Label.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Posts.
        /// </summary>
        internal static string Label_ForumPosts {
            get {
                return ResourceManager.GetString("Label.ForumPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Label_Friends {
            get {
                return ResourceManager.GetString("Label.Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        internal static string Label_GridView {
            get {
                return ResourceManager.GetString("Label.GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game.
        /// </summary>
        internal static string Label_InGame {
            get {
                return ResourceManager.GetString("Label.InGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Studio.
        /// </summary>
        internal static string Label_InStudio {
            get {
                return ResourceManager.GetString("Label.InStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        internal static string Label_JoinDate {
            get {
                return ResourceManager.GetString("Label.JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More.
        /// </summary>
        internal static string Label_LoadMore {
            get {
                return ResourceManager.GetString("Label.LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Label_Members {
            get {
                return ResourceManager.GetString("Label.Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Usernames.
        /// </summary>
        internal static string Label_PastUsername {
            get {
                return ResourceManager.GetString("Label.PastUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous usernames.
        /// </summary>
        internal static string Label_PastUsernames {
            get {
                return ResourceManager.GetString("Label.PastUsernames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Visits.
        /// </summary>
        internal static string Label_PlaceVisits {
            get {
                return ResourceManager.GetString("Label.PlaceVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Label_Playing {
            get {
                return ResourceManager.GetString("Label.Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;{0}\&quot;.
        /// </summary>
        internal static string Label_Quotation {
            get {
                return ResourceManager.GetString("Label.Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Label_Rank {
            get {
                return ResourceManager.GetString("Label.Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string Label_ReadMore {
            get {
                return ResourceManager.GetString("Label.ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse.
        /// </summary>
        internal static string Label_ReportAbuse {
            get {
                return ResourceManager.GetString("Label.ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Less.
        /// </summary>
        internal static string Label_ShowLess {
            get {
                return ResourceManager.GetString("Label.ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow View.
        /// </summary>
        internal static string Label_SlideshowView {
            get {
                return ResourceManager.GetString("Label.SlideshowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unblock this user?.
        /// </summary>
        internal static string Label_UnblockWarningBody {
            get {
                return ResourceManager.GetString("Label.UnblockWarningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string Label_UnblockWarningConfirm {
            get {
                return ResourceManager.GetString("Label.UnblockWarningConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string Label_Visits {
            get {
                return ResourceManager.GetString("Label.Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Label_WarningTitle {
            get {
                return ResourceManager.GetString("Label.WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to accept friend request..
        /// </summary>
        internal static string Message_AcceptFriendRequestError {
            get {
                return ResourceManager.GetString("Message.AcceptFriendRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please try again later.
        /// </summary>
        internal static string Message_AliasHasError {
            get {
                return ResourceManager.GetString("Message.AliasHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please avoid using full names or offensive language..
        /// </summary>
        internal static string Message_AliasIsModerated {
            get {
                return ResourceManager.GetString("Message.AliasIsModerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to block user. You may have blocked too many people..
        /// </summary>
        internal static string Message_BlockError {
            get {
                return ResourceManager.GetString("Message.BlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to block user..
        /// </summary>
        internal static string Message_BlockRequestError {
            get {
                return ResourceManager.GetString("Message.BlockRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you up to?.
        /// </summary>
        internal static string Message_ChangeStatus {
            get {
                return ResourceManager.GetString("Message.ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed! You may have blocked too many people..
        /// </summary>
        internal static string Message_ErrorBlockLimit {
            get {
                return ResourceManager.GetString("Message.ErrorBlockLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please check back in a few minutes..
        /// </summary>
        internal static string Message_ErrorGeneral {
            get {
                return ResourceManager.GetString("Message.ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to follow user..
        /// </summary>
        internal static string Message_FollowError {
            get {
                return ResourceManager.GetString("Message.FollowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to impersonate user..
        /// </summary>
        internal static string Message_ImpersonateUserError {
            get {
                return ResourceManager.GetString("Message.ImpersonateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no creations..
        /// </summary>
        internal static string Message_NoCreation {
            get {
                return ResourceManager.GetString("Message.NoCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unfriend user..
        /// </summary>
        internal static string Message_RemoveFriendError {
            get {
                return ResourceManager.GetString("Message.RemoveFriendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send friend request..
        /// </summary>
        internal static string Message_SendFriendRequestError {
            get {
                return ResourceManager.GetString("Message.SendFriendRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing....
        /// </summary>
        internal static string Message_Sharing {
            get {
                return ResourceManager.GetString("Message.Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unfollow user..
        /// </summary>
        internal static string Message_UnfollowError {
            get {
                return ResourceManager.GetString("Message.UnfollowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update status..
        /// </summary>
        internal static string Message_UpdateStatusError {
            get {
                return ResourceManager.GetString("Message.UpdateStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Please try again later..
        /// </summary>
        internal static string Response_TooManyAttempts {
            get {
                return ResourceManager.GetString("Response.TooManyAttempts", resourceCulture);
            }
        }
    }
}
