//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Feature {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameLaunchGuestMode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameLaunchGuestMode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Feature.GameLaunchGuestMode", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Action_Dialog_Close {
            get {
                return ResourceManager.GetString("Action.Dialog.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Action_Dialog_Login {
            get {
                return ResourceManager.GetString("Action.Dialog.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_Dialog_Ok {
            get {
                return ResourceManager.GetString("Action.Dialog.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Action_Dialog_SignUp {
            get {
                return ResourceManager.GetString("Action.Dialog.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now!.
        /// </summary>
        internal static string Action_Dialog_SignUpNow {
            get {
                return ResourceManager.GetString("Action.Dialog.SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To play games, chat with friends, or customize your avatar, you&apos;ll need an account. Sign up for a free account or log in to play now..
        /// </summary>
        internal static string Description_Dialog_SignUpOrLogin {
            get {
                return ResourceManager.GetString("Description.Dialog.SignUpOrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are playing in guest mode. To use all features available on Roblox, you will need to create an account. You have less than a day left before we require free sign up..
        /// </summary>
        internal static string Description_Dialog_SignUpTodayOneDayRemaining {
            get {
                return ResourceManager.GetString("Description.Dialog.SignUpTodayOneDayRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are playing in guest mode. To use all features available on Roblox, you will need to create an account. You have less than {0} days left before we require free sign up..
        /// </summary>
        internal static string Description_Dialog_SignUpTodaySomeDaysRemaining {
            get {
                return ResourceManager.GetString("Description.Dialog.SignUpTodaySomeDaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial period has ended. Please sign up to play games - it&apos;s free!.
        /// </summary>
        internal static string Description_Dialog_TrialOver {
            get {
                return ResourceManager.GetString("Description.Dialog.TrialOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are playing in guest mode. To use all features available on Roblox, you will need to create an account. You have 1 gameplay left before we require free sign up..
        /// </summary>
        internal static string Description_Dialog_YouArePlayingOneDayRemaining {
            get {
                return ResourceManager.GetString("Description.Dialog.YouArePlayingOneDayRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are playing in guest mode. To use all features available on Roblox, you will need to create an account. You have {0} gameplays left before we require free sign up..
        /// </summary>
        internal static string Description_Dialog_YouArePlayingSomeDaysRemaining {
            get {
                return ResourceManager.GetString("Description.Dialog.YouArePlayingSomeDaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Character.
        /// </summary>
        internal static string HeadingChooseCharacter {
            get {
                return ResourceManager.GetString("HeadingChooseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Avatar.
        /// </summary>
        internal static string Heading_ChooseAvatar {
            get {
                return ResourceManager.GetString("Heading.ChooseAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for a free account or log in!.
        /// </summary>
        internal static string Heading_Dialog_SignUpOrLogin {
            get {
                return ResourceManager.GetString("Heading.Dialog.SignUpOrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Today!.
        /// </summary>
        internal static string Heading_Dialog_SignUpToday {
            get {
                return ResourceManager.GetString("Heading.Dialog.SignUpToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have an account!.
        /// </summary>
        internal static string LabelHaveAccount {
            get {
                return ResourceManager.GetString("LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have an account.
        /// </summary>
        internal static string Label_HaveAccount {
            get {
                return ResourceManager.GetString("Label.HaveAccount", resourceCulture);
            }
        }
    }
}
