//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Feature {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Catalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Feature.Catalog", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Robux.
        /// </summary>
        internal static string Action_BuyRobux {
            get {
                return ResourceManager.GetString("Action.BuyRobux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Action_Dialog_AddGearOk {
            get {
                return ResourceManager.GetString("Action.Dialog.AddGearOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Action_Filter_Apply {
            get {
                return ResourceManager.GetString("Action.Filter.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Filter_Cancel {
            get {
                return ResourceManager.GetString("Action.Filter.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Action_Go {
            get {
                return ResourceManager.GetString("Action.Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Items.
        /// </summary>
        internal static string Action_ViewAllItems {
            get {
                return ResourceManager.GetString("Action.ViewAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Featured Items.
        /// </summary>
        internal static string Action_ViewFeaturedItems {
            get {
                return ResourceManager.GetString("Action.ViewFeaturedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add gear to your game, find an item in the catalog and click the Add to Game button. The item will automatically be allowed in game, and you&apos;ll receive a commission on every copy sold from your game page. (You can only add gear that&apos;s for sale.).
        /// </summary>
        internal static string Description_Dialog_AddGearBody {
            get {
                return ResourceManager.GetString("Description.Dialog.AddGearBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Shop.
        /// </summary>
        internal static string Heading_AvatarShop {
            get {
                return ResourceManager.GetString("Heading.AvatarShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Heading_CatalogCategory {
            get {
                return ResourceManager.GetString("Heading.CatalogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string Heading_CatalogPage {
            get {
                return ResourceManager.GetString("Heading.CatalogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string LabelAccessories {
            get {
                return ResourceManager.GetString("LabelAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Accessories.
        /// </summary>
        internal static string LabelAccessoryAll {
            get {
                return ResourceManager.GetString("LabelAccessoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string LabelAccessoryBack {
            get {
                return ResourceManager.GetString("LabelAccessoryBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        internal static string LabelAccessoryFace {
            get {
                return ResourceManager.GetString("LabelAccessoryFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string LabelAccessoryFront {
            get {
                return ResourceManager.GetString("LabelAccessoryFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        internal static string LabelAccessoryHair {
            get {
                return ResourceManager.GetString("LabelAccessoryHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hats.
        /// </summary>
        internal static string LabelAccessoryHats {
            get {
                return ResourceManager.GetString("LabelAccessoryHats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string LabelAccessoryNeck {
            get {
                return ResourceManager.GetString("LabelAccessoryNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder.
        /// </summary>
        internal static string LabelAccessoryShoulder {
            get {
                return ResourceManager.GetString("LabelAccessoryShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string LabelAccessoryWaist {
            get {
                return ResourceManager.GetString("LabelAccessoryWaist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string LabelAll {
            get {
                return ResourceManager.GetString("LabelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Animations.
        /// </summary>
        internal static string LabelAllAvatarAnimations {
            get {
                return ResourceManager.GetString("LabelAllAvatarAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Body Parts.
        /// </summary>
        internal static string LabelAllBodyParts {
            get {
                return ResourceManager.GetString("LabelAllBodyParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        internal static string LabelAllCategories {
            get {
                return ResourceManager.GetString("LabelAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Clothing.
        /// </summary>
        internal static string LabelAllClothing {
            get {
                return ResourceManager.GetString("LabelAllClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Collectibles.
        /// </summary>
        internal static string LabelAllCollectibles {
            get {
                return ResourceManager.GetString("LabelAllCollectibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Creators.
        /// </summary>
        internal static string LabelAllCreators {
            get {
                return ResourceManager.GetString("LabelAllCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Currency.
        /// </summary>
        internal static string LabelAllCurrency {
            get {
                return ResourceManager.GetString("LabelAllCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Featured Items.
        /// </summary>
        internal static string LabelAllFeatured {
            get {
                return ResourceManager.GetString("LabelAllFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        internal static string LabelAllTime {
            get {
                return ResourceManager.GetString("LabelAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations.
        /// </summary>
        internal static string LabelAnimations {
            get {
                return ResourceManager.GetString("LabelAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Price.
        /// </summary>
        internal static string LabelAnyPrice {
            get {
                return ResourceManager.GetString("LabelAnyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Animations.
        /// </summary>
        internal static string LabelAvatarAnimations {
            get {
                return ResourceManager.GetString("LabelAvatarAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestselling.
        /// </summary>
        internal static string LabelBestselling {
            get {
                return ResourceManager.GetString("LabelBestselling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Parts.
        /// </summary>
        internal static string LabelBodyParts {
            get {
                return ResourceManager.GetString("LabelBodyParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        internal static string LabelClothing {
            get {
                return ResourceManager.GetString("LabelClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectible Accessories.
        /// </summary>
        internal static string LabelCollectibleAccessories {
            get {
                return ResourceManager.GetString("LabelCollectibleAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectible Faces.
        /// </summary>
        internal static string LabelCollectibleFaces {
            get {
                return ResourceManager.GetString("LabelCollectibleFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectible Gear.
        /// </summary>
        internal static string LabelCollectibleGear {
            get {
                return ResourceManager.GetString("LabelCollectibleGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectibles.
        /// </summary>
        internal static string LabelCollectibles {
            get {
                return ResourceManager.GetString("LabelCollectibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces.
        /// </summary>
        internal static string LabelFaces {
            get {
                return ResourceManager.GetString("LabelFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        internal static string LabelFeatured {
            get {
                return ResourceManager.GetString("LabelFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Accessories.
        /// </summary>
        internal static string LabelFeaturedAccesories {
            get {
                return ResourceManager.GetString("LabelFeaturedAccesories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Animations.
        /// </summary>
        internal static string LabelFeaturedAnimations {
            get {
                return ResourceManager.GetString("LabelFeaturedAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Faces.
        /// </summary>
        internal static string LabelFeaturedFaces {
            get {
                return ResourceManager.GetString("LabelFeaturedFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Gear.
        /// </summary>
        internal static string LabelFeaturedGear {
            get {
                return ResourceManager.GetString("LabelFeaturedGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Packages.
        /// </summary>
        internal static string LabelFeaturedPackages {
            get {
                return ResourceManager.GetString("LabelFeaturedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string LabelFree {
            get {
                return ResourceManager.GetString("LabelFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string LabelGear {
            get {
                return ResourceManager.GetString("LabelGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gear.
        /// </summary>
        internal static string LabelGearAll {
            get {
                return ResourceManager.GetString("LabelGearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string LabelGearBuilding {
            get {
                return ResourceManager.GetString("LabelGearBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive.
        /// </summary>
        internal static string LabelGearExplosive {
            get {
                return ResourceManager.GetString("LabelGearExplosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string LabelGearMelee {
            get {
                return ResourceManager.GetString("LabelGearMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        internal static string LabelGearMusical {
            get {
                return ResourceManager.GetString("LabelGearMusical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string LabelGearNavigation {
            get {
                return ResourceManager.GetString("LabelGearNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string LabelGearPersonalTransport {
            get {
                return ResourceManager.GetString("LabelGearPersonalTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Up.
        /// </summary>
        internal static string LabelGearPowerUps {
            get {
                return ResourceManager.GetString("LabelGearPowerUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string LabelGearRanged {
            get {
                return ResourceManager.GetString("LabelGearRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string LabelGearSocial {
            get {
                return ResourceManager.GetString("LabelGearSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        internal static string LabelGenreAdventure {
            get {
                return ResourceManager.GetString("LabelGenreAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Genres.
        /// </summary>
        internal static string LabelGenreAll {
            get {
                return ResourceManager.GetString("LabelGenreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string LabelGenreBuilding {
            get {
                return ResourceManager.GetString("LabelGenreBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        internal static string LabelGenreComedy {
            get {
                return ResourceManager.GetString("LabelGenreComedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medieval.
        /// </summary>
        internal static string LabelGenreFantasy {
            get {
                return ResourceManager.GetString("LabelGenreFantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        internal static string LabelGenreFighting {
            get {
                return ResourceManager.GetString("LabelGenreFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        internal static string LabelGenreFPS {
            get {
                return ResourceManager.GetString("LabelGenreFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        internal static string LabelGenreFunny {
            get {
                return ResourceManager.GetString("LabelGenreFunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string LabelGenreHorror {
            get {
                return ResourceManager.GetString("LabelGenreHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medieval.
        /// </summary>
        internal static string LabelGenreMedieval {
            get {
                return ResourceManager.GetString("LabelGenreMedieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military.
        /// </summary>
        internal static string LabelGenreMilitary {
            get {
                return ResourceManager.GetString("LabelGenreMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naval.
        /// </summary>
        internal static string LabelGenreNaval {
            get {
                return ResourceManager.GetString("LabelGenreNaval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        internal static string LabelGenreNinja {
            get {
                return ResourceManager.GetString("LabelGenreNinja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naval.
        /// </summary>
        internal static string LabelGenrePirate {
            get {
                return ResourceManager.GetString("LabelGenrePirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPG.
        /// </summary>
        internal static string LabelGenreRPG {
            get {
                return ResourceManager.GetString("LabelGenreRPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string LabelGenreScary {
            get {
                return ResourceManager.GetString("LabelGenreScary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-Fi.
        /// </summary>
        internal static string LabelGenreSciFi {
            get {
                return ResourceManager.GetString("LabelGenreSciFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string LabelGenreSports {
            get {
                return ResourceManager.GetString("LabelGenreSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town and City.
        /// </summary>
        internal static string LabelGenreTownAndCity {
            get {
                return ResourceManager.GetString("LabelGenreTownAndCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string LabelGenreTutorial {
            get {
                return ResourceManager.GetString("LabelGenreTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military.
        /// </summary>
        internal static string LabelGenreWar {
            get {
                return ResourceManager.GetString("LabelGenreWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        internal static string LabelGenreWestern {
            get {
                return ResourceManager.GetString("LabelGenreWestern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        internal static string LabelGenreWildWest {
            get {
                return ResourceManager.GetString("LabelGenreWildWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heads.
        /// </summary>
        internal static string LabelHeads {
            get {
                return ResourceManager.GetString("LabelHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Favorited.
        /// </summary>
        internal static string LabelMostFavorited {
            get {
                return ResourceManager.GetString("LabelMostFavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Resellers.
        /// </summary>
        internal static string LabelNoResellers {
            get {
                return ResourceManager.GetString("LabelNoResellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offsale.
        /// </summary>
        internal static string LabelOffSale {
            get {
                return ResourceManager.GetString("LabelOffSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string LabelPackages {
            get {
                return ResourceManager.GetString("LabelPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants.
        /// </summary>
        internal static string LabelPants {
            get {
                return ResourceManager.GetString("LabelPants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Day.
        /// </summary>
        internal static string LabelPastDay {
            get {
                return ResourceManager.GetString("LabelPastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Week.
        /// </summary>
        internal static string LabelPastWeek {
            get {
                return ResourceManager.GetString("LabelPastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (High to Low).
        /// </summary>
        internal static string LabelPriceHighFirst {
            get {
                return ResourceManager.GetString("LabelPriceHighFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Low to High).
        /// </summary>
        internal static string LabelPriceLowFirst {
            get {
                return ResourceManager.GetString("LabelPriceLowFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Updated.
        /// </summary>
        internal static string LabelRecentlyUpdated {
            get {
                return ResourceManager.GetString("LabelRecentlyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        internal static string LabelRelevance {
            get {
                return ResourceManager.GetString("LabelRelevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roblox.
        /// </summary>
        internal static string LabelRoblox {
            get {
                return ResourceManager.GetString("LabelRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robux.
        /// </summary>
        internal static string LabelRobux {
            get {
                return ResourceManager.GetString("LabelRobux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirts.
        /// </summary>
        internal static string LabelShirts {
            get {
                return ResourceManager.GetString("LabelShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Shirts.
        /// </summary>
        internal static string LabelTShirts {
            get {
                return ResourceManager.GetString("LabelTShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Creations.
        /// </summary>
        internal static string Label_AllCommunityCreations {
            get {
                return ResourceManager.GetString("Label.AllCommunityCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Featured Items.
        /// </summary>
        internal static string Label_AllFeaturedItems {
            get {
                return ResourceManager.GetString("Label.AllFeaturedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Genres.
        /// </summary>
        internal static string Label_AllGenres {
            get {
                return ResourceManager.GetString("Label.AllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Premium Items.
        /// </summary>
        internal static string Label_AllPremiumItems {
            get {
                return ResourceManager.GetString("Label.AllPremiumItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon.
        /// </summary>
        internal static string Label_Amazon {
            get {
                return ResourceManager.GetString("Label.Amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Label_BreadCrumb_Free {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {genreName1} or {genreName2}.
        /// </summary>
        internal static string Label_BreadCrumb_GenreOrText {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.GenreOrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: {genreCount} selected.
        /// </summary>
        internal static string Label_BreadCrumb_GenreSelectedText {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.GenreSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        internal static string Label_BreadCrumb_Group {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {price} and above.
        /// </summary>
        internal static string Label_BreadCrumb_PriceAbove {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.PriceAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {price} and below.
        /// </summary>
        internal static string Label_BreadCrumb_PriceBelow {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.PriceBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {startNumber} - {endNumber} of {resultsCount} Results.
        /// </summary>
        internal static string Label_BreadCrumb_ResultsCount {
            get {
                return ResourceManager.GetString("Label.BreadCrumb.ResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        internal static string Label_Bundle {
            get {
                return ResourceManager.GetString("Label.Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        internal static string Label_Bundles {
            get {
                return ResourceManager.GetString("Label.Bundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By {linkStart}{creator}{linkEnd}.
        /// </summary>
        internal static string Label_ByCreatorLink {
            get {
                return ResourceManager.GetString("Label.ByCreatorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string Label_Card_CreatorBy {
            get {
                return ResourceManager.GetString("Label.Card.CreatorBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was.
        /// </summary>
        internal static string Label_Card_PriceWas {
            get {
                return ResourceManager.GetString("Label.Card.PriceWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining:.
        /// </summary>
        internal static string Label_Card_Remaining {
            get {
                return ResourceManager.GetString("Label.Card.Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Label_CategoryAttributes {
            get {
                return ResourceManager.GetString("Label.CategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Label_CategoryType {
            get {
                return ResourceManager.GetString("Label.CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Community Creations.
        /// </summary>
        internal static string Label_CommunityCreations {
            get {
                return ResourceManager.GetString("Label.CommunityCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gear to Your Game.
        /// </summary>
        internal static string Label_Dialog_AddGearTitle {
            get {
                return ResourceManager.GetString("Label.Dialog.AddGearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes.
        /// </summary>
        internal static string Label_Emotes {
            get {
                return ResourceManager.GetString("Label.Emotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Label_Favorites {
            get {
                return ResourceManager.GetString("Label.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Bundles.
        /// </summary>
        internal static string Label_FeaturedBundles {
            get {
                return ResourceManager.GetString("Label.FeaturedBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Emotes.
        /// </summary>
        internal static string Label_FeaturedEmotes {
            get {
                return ResourceManager.GetString("Label.FeaturedEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Items on {spanStart}{roblox}{spanEnd}.
        /// </summary>
        internal static string Label_FeaturedItemsOnRoblox {
            get {
                return ResourceManager.GetString("Label.FeaturedItemsOnRoblox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Time.
        /// </summary>
        internal static string Label_Filter_ByTime {
            get {
                return ResourceManager.GetString("Label.Filter.ByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Label_Filter_Category {
            get {
                return ResourceManager.GetString("Label.Filter.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Label_Filter_Creator {
            get {
                return ResourceManager.GetString("Label.Filter.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Label_Filter_Filter {
            get {
                return ResourceManager.GetString("Label.Filter.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Label_Filter_Filters {
            get {
                return ResourceManager.GetString("Label.Filter.Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string Label_Filter_Genre {
            get {
                return ResourceManager.GetString("Label.Filter.Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Label_Filter_Hide {
            get {
                return ResourceManager.GetString("Label.Filter.Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Label_Filter_Price {
            get {
                return ResourceManager.GetString("Label.Filter.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Label_Filter_PriceMax {
            get {
                return ResourceManager.GetString("Label.Filter.PriceMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Label_Filter_PriceMin {
            get {
                return ResourceManager.GetString("Label.Filter.PriceMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Label_Filter_PriceTo {
            get {
                return ResourceManager.GetString("Label.Filter.PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Label_Filter_Show {
            get {
                return ResourceManager.GetString("Label.Filter.Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Label_Filter_Sorting {
            get {
                return ResourceManager.GetString("Label.Filter.Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable Items.
        /// </summary>
        internal static string Label_Filter_UnavailableItems {
            get {
                return ResourceManager.GetString("Label.Filter.UnavailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Only.
        /// </summary>
        internal static string Label_GoogleOnly {
            get {
                return ResourceManager.GetString("Label.GoogleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOS.
        /// </summary>
        internal static string Label_Ios {
            get {
                return ResourceManager.GetString("Label.Ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Label_Mobile {
            get {
                return ResourceManager.GetString("Label.Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Label_New {
            get {
                return ResourceManager.GetString("Label.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string Label_Premium {
            get {
                return ResourceManager.GetString("Label.Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string Label_Recommended {
            get {
                return ResourceManager.GetString("Label.Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Items for You.
        /// </summary>
        internal static string Label_RecommendedItemsForYou {
            get {
                return ResourceManager.GetString("Label.RecommendedItemsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rthro.
        /// </summary>
        internal static string Label_Rthro {
            get {
                return ResourceManager.GetString("Label.Rthro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Label_Sale {
            get {
                return ResourceManager.GetString("Label.Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_SearchField {
            get {
                return ResourceManager.GetString("Label.SearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        internal static string Label_SeeAll {
            get {
                return ResourceManager.GetString("Label.SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox.
        /// </summary>
        internal static string Label_Xbox {
            get {
                return ResourceManager.GetString("Label.Xbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors exist in Filter tab.
        /// </summary>
        internal static string Response_Error_Filter {
            get {
                return ResourceManager.GetString("Response.Error.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        internal static string Response_GenericError {
            get {
                return ResourceManager.GetString("Response.GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        internal static string Response_NoItemsFound {
            get {
                return ResourceManager.GetString("Response.NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search did not find items for sale. Unavailable items displayed below..
        /// </summary>
        internal static string Response_NoSaleItemsFromSearch {
            get {
                return ResourceManager.GetString("Response.NoSaleItemsFromSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to place on sale.
        /// </summary>
        internal static string Response_PlacedOnSaleFailure {
            get {
                return ResourceManager.GetString("Response.PlacedOnSaleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully placed on sale.
        /// </summary>
        internal static string Response_PlacedOnSaleSuccess {
            get {
                return ResourceManager.GetString("Response.PlacedOnSaleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to take off sale.
        /// </summary>
        internal static string Response_TakenOffSaleFailure {
            get {
                return ResourceManager.GetString("Response.TakenOffSaleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully taken off sale.
        /// </summary>
        internal static string Response_TakenOffSaleSuccess {
            get {
                return ResourceManager.GetString("Response.TakenOffSaleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog temporarily unavailable. Please try again later..
        /// </summary>
        internal static string Response_TemporarilyUnavailable {
            get {
                return ResourceManager.GetString("Response.TemporarilyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going too fast! Try again in a minute.&quot;.
        /// </summary>
        internal static string Response_Throttled {
            get {
                return ResourceManager.GetString("Response.Throttled", resourceCulture);
            }
        }
    }
}
